### PR TITLE
[WIP] Added #3520: Add ability to map users to multiple companies with FullMultipleCompanySupport

### LINKED ISSUE #3520: Multiple Company mangement
#### Expected Behavior (or desired behavior if a feature request)

Is it possible to have a User be a manager (via permissions?) across multiple companies?
*Or* can a single Company have 'sub-divisions' within it?

-----

#### Actual Behavior

A person can only be a member/manager of one Company

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.4 build 12 (gf7e4fca)
- What OS and web server you're running Snipe-IT on - Debian 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - N/A
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44624723-multiple-company-mangement?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Toreg87**
# Description

We have a hierarchical set of companies grouped in multiple layers:
 a) the upper layer must have access to all companies
 b) the lowest layer must be scoped to only one company
 c) the middle layer must have access to multiple companies of the lowest layer, but not all of them

a) and b) is possible with FullMultipleCompanySupport and super user, but c) is currently not supported.

To accomplish this, I propose the concept of "mapped" companies.
Users with a mapped company can see and update all resources of the mapped company according to the users permissions, just like the "primary" company.

A new mapping table is created and linked to users and companies and the company scoping function is updated accordingly.
The mapping table only contains additional mappings, not the "primary" company of the user.
In the user edit view a new tab is created to map users to companies:
comopany_mappings

The validation logic must be changed for this. Currently a scoped user can't change the company.
Now it must be possible for users with mapped companies to choose between companies.
To do this, two changes are needed:
 - the company selectlist gets scoped to the primary and the mapped companies
 - a new validator is introduced to validate if the user is allowed to choose a company or if a company is required. This validator handles input through the UI and the API

The logic if a user is edited must be changed accordingly:
- If a different "primary" company is assigned to a user, the mapping table must be updated.
- Bulk editing this must also be supported.
- If a user gets cloned, the mappings must be cloned.

I implemented this feature with performance and backward compatibility in mind. There is no overhead if FullMultipleCompanySupport is disabled.
The feature is fully optional, there is only minimal overhead if FullMultipleCompanySupport is enabled and no mappings are used.

This is WIP for now, there are several areas that needs further work:

- There are no permission checks for updating the mappings. My plan is to go with the solution for groups: only super users should be permitted to update the mappings
- There is no localization for the new UI elements and the validator
- I focused on assets for now. The validator must be applied to every other part of the system
- There is no documentation update for now

Fixes #3520 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

I ran the following tests manually for the 5 different cases: FullMultipleCompanySupport disabled, super user, user with no mappings, user with mappings, user with no company

- show companies (UI and API)
- show assets (UI and API)
- create assets (UI and API)
- edit assets (UI and API)
- show users (UI and API)
- create users and mappings
- edit users (change company, change mappings)
- clone user
- bulk edit users

I found a few existing inconsistencies here:
- Scoped users can see all companies and get 403 errors if they try to view another company
- Scoped users can see all departments and get 403 errors if they try to view departments from other companies -> see #9798
- It is possible for a scoped user with permissions to create or edit a user to set the company_id to an arbitrary value

I will address these separately later.

**Test Configuration**:
* PHP version: 7.4
* MySQL version: mariadb 10.4
* Webserver version: apache 2.4.47
* OS version: Windows 10

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by uberbrady** [comment]
I don't think we'll be able to take this one, I'm afraid. I'm really sorry - it's one of the nicer pull requests that we've gotten, and it's well-thought-out, and I love your communicativeness and I love your openness and discussion, and the code itself looks great.

But unfortunately, the project is as successful as it is by being easy-to-use, and being simple. This adds a large set of complexity for a feature-set that, to be frank, is not going to be useful for the majority of our users. So we will have to regretfully decline.

Thank you, again, for your extremely well-thought-out pull request. Please don't be discouraged from submitting again; your work looks great and we'd love to take it if we believe it will fit well within the product.

**Comment by Toreg87** [comment]
@uberbrady this is a little bit sad but understandable. I completed my code and will carry the changes in my repository, as I really need this feature for my company. I will forward port this to new versions in the future. In case someone else is interested in this, the code is here: https://github.com/Toreg87/snipe-it/tree/feature/master_fmcs_map_multiple_companies
This is based on the upstream/master branch.

I will continue to work on this project and submit other changes if I find bugs or add useful features.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/Toreg87/snipe-it">GitHub - Toreg87/snipe-it at feature/master_fmcs_map_multiple_companies</a></strong></div><div>A free open source IT asset/license management system - GitHub - Toreg87/snipe-it at feature/master_fmcs_map_multiple_companies</div></blockquote>

**Comment by tlubas01** [comment]
Hello, I'm very interested in such feature. Toreg87 - could you help me to implement it ? please contact me taal  (at)  poczta.fm

**Comment by Toreg87** [comment]
@tlubas01 I have this feature running in production since a few years. You can find the commit in my own_master branch at: https://github.com/Toreg87/snipe-it/commits/own_master/
Due to lack of time, this is currently based on V6.4.1. I rebase this branch from time to time to newer versions.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/Toreg87/snipe-it">Commits · Toreg87/snipe-it</a></strong></div><div>A free open source IT asset/license management system - Commits · Toreg87/snipe-it</div></blockquote>

**Comment by tlubas01** [comment]
Thank you for quick answer
Ok then i should do fresh install from your branch or install 6.4.1 and update somehow ?
regards,
Tomek

**Comment by Toreg87** [comment]
I would install stock 6.4.1 and switch to my branch afterwards. Then run php artisan migrate to get the database changes.

**Comment by tlubas01** [comment]
@Toreg87 [Toreg87]
ok, I have 6.4.1 working, php v8.0 or 8.1
I did git merge from your repo orgin/master
I see no changes, no additional options for user, What should I do now? 
When i change branch to remotes/orgin/feature/master_fmcs_map_multiple_companies service stops working, and many errors is present. Composer and artisan fails.
 
Please tell me what version of PHP should i use. and what else should i do to apply multicompany changes without errors ?

**Comment by tlubas01** [comment]
> I would install stock 6.4.1 and switch to my branch afterwards. Then run php artisan migrate to get the database changes.

Ok, i made it :) Thank you.

**Comment by Toreg87** [comment]
@tlubas01 I rebased my own_master branch to V7.0.13 and successfully tested the changes on my local development environment.

**Pull request closed without merging**
