### PR TITLE
Fixes footer from being covered if it is an extra long footer.

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
Footer would be covered up by the div wrapper if the footer went more than one line. I added more height to the footer if additional footer is present to solve this issue.
BEFORE:
image

AFTER:
image

Fixes #SC-15580

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by snipe — CHANGES_REQUESTED** [review]
Hm, that will always make the footer 100 pixels though, right? I don't think we want that space if there's no need for it (with a shorter footer I mean.)

**Comment by Godmartinz** [comment]
changed the approach, now a height addition will be added if a `footer_text` is present.

**Comment by Godmartinz** [comment]
This still seems to be needed @snipe . Is there something I need to change here?

**Comment by Godmartinz** [comment]
haunted and condemned! https://github.com/snipe/snipe-it/pull/12832

**Pull request closed without merging**
