### PR TITLE
Added Status Label names to Asset history/ Action log 

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
This adds status label changes to the asset history/ action logs. 
Before:
image

After:
image

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tiennv3011** [comment]
image
activity report not work in v6.1..2

**Comment by snipe** [comment]
@tiennv3011 6.1.2 was a while ago. This PR is unrelated to anything that might have been broken in 6.1.2, but regardless, you should upgrade anyway.

**Comment by tiennv3011** [comment]
> @tiennv3011 6.1.2 was a while ago. This PR is unrelated to anything that might have been broken in 6.1.2, but regardless, you should upgrade anyway.

Do I need to upgrade the Snipe IT version? I'm currently experiencing errors when upgrading to the latest version :(

**Comment by snipe** [comment]
> Do I need to upgrade the Snipe IT version? I'm currently experiencing errors when upgrading to the latest version :(

I mean, nobody needs to do anything, but if you want that problem fixed, you probably want to upgrade. If you're having trouble upgrading, please open a separate ticket about that, and fill in all of the bits of information we ask for in the ticket template.

**Comment by squintfox** [comment]
@Godmartinz Just as a comment, this PR is awesome.  Really a huge benefit for our implementation.

**Comment by snipe** [comment]
@Godmartinz - I don't think there's any harm in merging this, but it won't be alive for long, given the rewriting of the logs stuff I'm working on. It's still an excellent effort. It's still looking up what the status label is *now* versus what it was when it was changed, but it's better than what we have.

**Pull request merged**
