### PR TITLE
Bumped dependencies

### PR DESCRIPTION
**Pull request by marcusmoore**
# Description

This PR bumps the following dependencies:
- `nyholm/psr7`: from 1.5.1 to 1.6.1
- `guzzlehttp/psr7`: from 2.4.0 to 2.4.5

### CODE REVIEW

**Comment by snipe** [comment]
What’s the reason for this bump?

**Comment by marcusmoore** [comment]
- [Improper Input Validation in nyholm/psr7](https://github.com/advisories/GHSA-wjfc-pgfp-pv9c)
- [Improper header name validation in guzzlehttp/psr7](https://github.com/advisories/GHSA-wxmh-65f7-jcvw)

**Comment by marcusmoore** [comment]
@snipe I just double-checked this is installable on PHP 7.4 by:

1. Switching to this branch
2. Running `valet isolate php@7.4`
3. Running `valet composer install`
4. Making sure composer didn't yell at me (it completed successfully)

**Comment by snipe** [comment]
Can you resolve these conflicts? If so, I'll happily take it :)

**Comment by marcusmoore** [comment]
@snipe done 😄

**Comment by snipe** [comment]
Obrigada!

**Pull request merged**
