### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by snipe**

### CODE REVIEW

**Comment by snipe** [comment]
This needs some tweaks, since it changes the format on the language directories. (This is autogenerated from Crowding, as I'm working on better built-in syncing.)

**Comment by snipe** [comment]
This CrowdIn integration still needs some work. It will end up changing the short (legacy) two-letter language codes into `xx-YY`, which isn't *bad* exactly, but it would mean that unless you were using a version that already had a `xx-YY` directory in the `resources/lang/` directory, it would likely default back to english, which could cause some confusion. I could write a migration, I suppose but that seems like a pain. BUT we do have quite a few of the two-letter versions :( 

Screen Shot 2022-06-13 at 9 12 05 PM

@uberbrady any thoughts here?

**Comment by uberbrady** [comment]
I mean some ability to automate changing this for our users would be at least nice - we have to make some assumptions though - 

- `en` becomes `en-US` but not `en-GB`
- `es` becomes `es-MX` but not `es-ES`

etc. Which would be weird. 

Maybe one thing we could do would be put in some symlinks? I don't know how well these would be handled on Windows systems though. That way we could throw in a symlink from `en` to `en-US`, etc.

**Comment by uberbrady** [comment]
The other concern I did want to voice was that if we *did* rename something from `en-us` to `en-US` that would be extremely bad for any of our users who are on case-sensitive filesystems - they would have a very bad time being able to run  upgrades.

But luckily you assured me that we are OK in that regard, so that's at least one less thing.

**Pull request closed without merging**
