### PR TITLE
Fixed #9129: add missing function formatDatalistSafe to snipeit_modal.js

### LINKED ISSUE #9129: Items in create model do not show. /hardware/create
#### Please confirm you have done the following before posting your bug report:

- [Yes] I have enabled debug mode 

- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Items in create model do not show.

**To Reproduce**
1. Go to 'http://192.168.1.12/hardware/create'
2. Click on 'Create Asset Model'
3. Scroll down to 'Manufacturer:'
4. See error  : Not listed.

**Expected behavior**
Help fix the problem.

**Screenshots**
[https://drive.google.com/file/d/1lYuT1j3fMjjthmWQSjgvO2rh7KBfXEWP/view?usp=sharing](url)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.1 - build 5811 (master)
 - OS: Windows Server 2016
 - Web Server: ISS
 - PHP Version 7.4.1
--

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro
 - Browser Crome
 - Version  88.0.4324.150

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- storage/logs [https://drive.google.com/file/d/1E5_K84DcakMXC2GhUoZC9DYsneYlX6qq/view?usp=sharing](url)
- extension=php_mysqli.dll
extension=php_mbstring.dll
extension=php_gd2.dll
extension=php_curl.dll
extension=php_exif.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_fileinfo.dll
[PHP_LDAP]
extension=php_ldap.dll

**Additional context**
- Upgrade from v5.0.10 to v5.1.1
- OS Windows Server 2016  running Snipe-IT on ISS
- What method you used to install Snipe-IT : Git-64-bit
- The database has not changed. But I just changed the Password for Administrator Go before upgrading .

### PR DESCRIPTION
**Pull request by sw-mreyes**
# Description

Added the function formatDatalistSafe from `resources/assets/js/snipeit.js` to `resources/assets/js/snipeit_modals.js`.
This will fix the `Uncaught Reference Error` when loading the `new model` modal from `/hardware/create`

Fixes #9129

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test that the new model modal works again.
  1. Click Create a new Asset,
  2. click the `new` Button next to the Model dropdown
  3. Fill in the fields, note that the dropdowns within the modal work again
  4. create the model and subsequently the asset, both seemed to work
- Test that other modals still work
  1. `/consumables/create ➡ Location ➡ New` works
  2. `/hardware/create ➡ Checkout to Location ➡ New` works

**Test Configuration**:
* PHP version: `7.2.24-0ubuntu0.18.04.7`
* MySQL version `mysql:5.6 `
* Webserver version `nginx/1.18.0`
* OS version `Ubuntu 20.04.1 LTS`

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings (compiled with `npm run production`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
@uberbrady can you please review when you get a moment? I'm not sure where/how this regression happened - the modals js should be pulled into all.js when npm run is fired off. Thanks!

**Comment by uberbrady** [comment]
I can replicate this bug on my latest checkout of develop, when I rebuilt the assets.

It looks like we have two copies of the old `formatDatalist` JS function - one in `snipeit.js` - 
https://github.com/snipe/snipe-it/blob/ff341caf345bf253f3d7b4e74f5c678809dddfc4/resources/assets/js/snipeit.js#L328

And one in `snipeit_modals.js` - 
https://github.com/snipe/snipe-it/blob/ff341caf345bf253f3d7b4e74f5c678809dddfc4/resources/assets/js/snipeit_modals.js#L162

This change just does the same thing for `formatDatalistSafe` - which did *not* have two copies rolling around.

I'm going to take a stab at seeing if I can pull the `formatDatalistSafe` function out to a global level so there's only one copy. Duping code around is not a thing I like to do, if we can avoid it. I won't spend too much time on it though.

**Comment by snipe** [comment]
@uberbrady is it okay if I merge this for now and we can refactor later?

**Comment by uberbrady** [comment]
@snipe My first pass at doing this failed, so I am going to give up on my approach. just need to test that this fix actually fixes it. So give me a few minutes.

**Review by uberbrady — APPROVED** [review]
Yeah, this fixes it. There's some other jankiness in the display but I'll handle that separately.

Thanks for the catch, @sw-mreyes !!!

**Pull request merged**
