### PR TITLE
Last Checkin Date added to Hardware View and Index

### PR DESCRIPTION
**Pull request by akemidx**
# Description
We were not showing the `last_checkin` date on the hardware view or index. This is a field in the hardware table and this PR adds in being able to see that data.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

tested locally via test instance

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by akemidx** [comment]
I commented out the nulling out of the`last_checkout` date. But I can revert that easy for this PR.

**Comment by snipe** [comment]
@akemidx can you resolve those conflicts for me?

**Comment by snipe** [comment]
@akemidx Make sure you test the sorting and searching in the UI and API on changes like this.

Screenshot 2024-03-27 at 8 28 43 PM

Sorting isn't working currently. I'll fix it, but it's something to keep in mind while testing changes moving forward.

**Comment by snipe** [comment]
@akemidx see #14516 for the fix. If we want to allow sorting on a DB field that's actually on the table itself (not a relation), it needs to be added to the `$allowed_columns` array so we know it's a straightforward sort with no complicated relationships going on. That `$allowed_columns` array exists to "allow list" known columns so people can't cause 500s by trying to sort on an asset table field that doesn't exist.

**Pull request merged**
