### PR TITLE
Fixed Translation String: wrong key at request canceled message

### PR DESCRIPTION
**Pull request by julian-piehl**
# Description

The translation key misses an "ed" at the end.

### CODE REVIEW

**Comment by snipe** [comment]
Thanks for this! We always appreciate folks taking the time to help out with translations. We don't currently manage translations through Pull Requests however, only through the CrowdIn platform. You can find more info on that here: https://snipe-it.readme.io/docs/translations

<blockquote><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>

**Comment by julian-piehl** [comment]
I think you understand me wrong @snipe.
Not the translation is wrong. The translation key is wrong

trans('key');

At one point the key `admin/hardware/message.requests.cancel` is used, but the right key is `admin/hardware/message.requests.canceled`

**Comment by julian-piehl** [comment]
> Thanks for this! We always appreciate folks taking the time to help out with translations. We don't currently manage translations through Pull Requests however, only through the CrowdIn platform. You can find more info on that here: https://snipe-it.readme.io/docs/translations

I think you understand me wrong @snipe.
Not the translation is wrong. The translation key is wrong

trans('key');

At one point the key `admin/hardware/message.requests.cancel` is used, but the right key is `admin/hardware/message.requests.canceled`

**Comment by snipe** [comment]
Got it - thanks for the clarification! 

Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by julian-piehl** [comment]
Done :D

**Comment by snipe** [comment]
Awesome, thanks!!

**Pull request merged**
