### PR TITLE
Feature to show location details recursively

### PR DESCRIPTION
**Pull request by Nevets82**
# Feature to show location details recursively
I gave feature request #4546 and #7126 a try ;-)

### Features
* Added child locations to location detail page;
* Added support to recursively show location user/assets/components/child locations;

### Usage
* This feature can be activated/deactivated by clicking the button 'Include/Exclude Child Locations' on the location details page;

### Remarks
* The top most location can at most have 255 child locations (PHP recursive method limit);
* I do not know how the translations work, I added my two strings to the english resource file. is this OK?

### CODE REVIEW

**Comment by ColinMcNeil** [comment]
We currently have 17000 locations. This would absolutely cripple our deployment, but I think it would be cool for smaller orgs. I think it should be an env setting as well.

**Comment by Nevets82** [comment]
Yes, you'r probably right. I will have a look on how to disable this feature. Thanks for your feedback.

**Comment by Nevets82** [comment]
In the meanwhile I redesigned the location view.blade to display tabs (like most other screens) and I also added the location's accessories and consumables.

**Comment by marrodox** [comment]
Thank you so much for giving this a try, this is critical for my deployment. I had submitted #7155 for this issue, so you'd be solving that as well :)

**Comment by snipe** [comment]
Did this ever get optimized for very large sets of assets? I'm not even sure we want to make this an optional feature - and if so, it shouldn't be in the .env, it should be in the settings panel. People who are unaware of the setting will just assume the system sucks and is slow.

**Comment by Nevets82** [comment]
No I did not further optimize this. I am not even sure this actually would be that big of a performance problem as paging is still in effect. The only problem I see is collecting the location id's recurssively (maybe there is a better SQL way). But we could still make this optional and hide the corresponding button. That way we can all test this in our environments.

**Comment by snipe** [comment]
Okay - if you can resolve the merge conflicts, I have a database laying around with a bunch of assets in it, which should hopefully let us test in volume situations.

**Comment by Nevets82** [comment]
@snipe you should be able to test this now. By clicking on the 'Include/Exclude Child Locations' button you should be able to see the result.
image

**Review by uberbrady — CHANGES_REQUESTED** [review]
This looks quite cleanly executed. I think I'm comfortable with the limit of 256-levels-deep on child locations; it seems bonkers to want more than that, and if you do I'm fine with saying just a plain simple 'nope!' I was trying to imagine a clever way of grabbing *all* locations and doing the looping and stuff in PHP in order to grab the Locations hierarchy, but I just don't think that's going to be a problem. Maybe we end up having to put an index on `parent_id` in Locations, if we don't have one (it seems like we don't), if we end up needing it? That's doable. If we need to optimize it, we certainly can.

This also seems like an optional feature, default-off, where you have to click on a something to make it execute. It only shows up when you're in in the Locations/view blade. And that does a new thing that we didn't do before. So if it *does* break, it'd only break if you explicitly used it. It does certainly add a new API parameter, but, again, if you don't use it, it won't bite you (if it bites at all, which I don't think it will).

So I'll definitely defer to the boss on any/all UI issues that could be a concern, but I think it seems pretty safe to accept. If you don't use it, it won't hurt you. If you do, this provides brand-new functionality that we didn't have before. So it seems good, all-around.

Some conflicts we'll have to resolve during the process (a lot has happened over a very long time), but this seems worth it, and with low enough risk. @Nevets82 any chance you're still around and can bring this up to merge cleanly against the latest `develop` branch? You submitted this a long, long time ago so it's totally fair if you aren't now.

**Pull request closed without merging**
