### PR TITLE
Fixed license serial gate in markdown

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

This adds a terenary on the license_seat->user gate check in the markdown for license serials

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Thanks @Godmartinz - can you tell me what specific problem this was solving?

**Comment by Godmartinz** [comment]
@snipe When a license is checked out to an asset and that asset does not have an assigned_to user... that would make the license_seat->user check fail causing an exception with the markdown.

**Comment by snipe** [comment]
Ah, is this why that one user wasn't getting their license checkout emails?

**Comment by Godmartinz** [comment]
undecided, but possibly? This was a bug found in the process of debugging. But there is a chance that it was messing up the mail function as a whole for licenses. Would like to merge this and retest on their instance. Continuing to explore other ways the license to user checkout email could be messing up though.

**Pull request merged**
