### PR TITLE
Ensure schedule analysis job never runs on forked repos

### PR DESCRIPTION
**Pull request by bestlong**

### CODE REVIEW

**Comment by snipe** [comment]
Why would we want this? Wouldn't you want to know that it doesn't pass the security scan before opening a PR?

**Comment by uberbrady** [comment]
Could there be a financial implication for other forks, where they have to pay for Github actions and they maybe don't want to? I think once the PR is submitted to us the scan should still run, right? Not quite sure.

**Comment by snipe** [comment]
I don't know - Codacy doesn't cost anything since we're open source.

**Comment by snipe** [comment]
@bestlong I merged this, but please answer our inquiries in the future. This seems harmless enough, but we'd appreciate an answer if you'd like things merged.

**Pull request merged**
