### PR TITLE
Feature/Fix/Refactor components/consumables/accessories to be equal with suppliers/manufacturers

### PR DESCRIPTION
**Pull request by mikeroq**
# Description

This is a rough draft of bring components/consumables/accessories more in line with each other in terms of suppliers/manufacturers. Also updated some layouts. 

Components didn't have a supplier or a manufacturer. Added
Consumables didn't have a supplier. Added

Modified view layout of components, consumables, and accessories to be the same. 
Updated manufacturer and supplier views to reflect addition of components/consumables.
Ensured components, consumables, and accessories had history tabs. Updated the observers to log the changes to the fields like on assets.

Added no results alert instead of rendering an empty data table on those pages, like on asset view.

Added more fields to display on view page.

Added Suppliers presenter.

Kinda outside the scope but added `fa-fw` to the navigation icons for better alignment. Company view didn't have an update button, added an action menu with update link. 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [x ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
For the things that are missing, thanks for that - but in terms of making layout changes (and table results changes, etc), it's probably better if you have a conversation with me about them. I determine what the layouts should look like, and am often likely already working on some of these things.

**Comment by snipe** [comment]
Also re: things that were "missing" from the API controllers, sometimes that's on purpose for loading/speed issues, so always be careful with those. We've definitely pulled some stuff that wasn't used often and was slowing things down a lot.

**Comment by snipe** [comment]
I'd like to see these broken down into much more bite-sized PRs. 39 files changes already for a WIP is more than I generally want to handle - and migrations should always be a conversation. Sometimes "missing" things are an oversight, sometimes they're a choice, and it's in everyone's best interest if we have those convos sooner rather than later so we don't all end up wasting our time on stuff that may or may not be merged. One fix, one PR. Mixing them all together makes it really hard to review and pick out things that we'd be willing to take versus ones we're not interested in at this time.

**Comment by mikeroq** [comment]
Thanks for the feedback. I'll admit I'm out of my depth here. I'll try to separate this out and tone down the changes.

**Comment by snipe** [comment]
A lot of what you have here is GREAT! It's just overwhelming to see a large PR like this, and there's some stuff we should probably talk about. Love the direction though. I'd definitely at least separate out the API changes from the layout changes. It will make it a lot easier to digest.

**Pull request closed without merging**
