### PR TITLE
Added Redirect options to asset check in/out

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

This adds asset redirect options back to the assigned asset, the person/place/thing it is being checked out to, or back to all assets. This remembers your last choice and keeps that choice stored in the session.
image

Check out Options:
image

Check in Options:
image

This creates a partial that is named `redirect-submit-options-blade.php` this dynamically takes in the variables needed in the example pictures and can shrink the code size a tiny bit now and later.

This also is setup to add on redirect options for other check in/out processes in the future. But that will require a bit of refactoring and they should probably be in separate PRs.

Fixes # [sc-1405]

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by snipe — CHANGES_REQUESTED** [review]
Looks like we've got some failing tests here: 

1) Tests\Feature\Checkins\AssetCheckinTest::testAssetCanBeCheckedIn
Expected response status code [201, 301, 302, 303, 307, 308] but received 500.

Also, can we add some spacing between that dropdown button and the submit button? It's jammed together right now.

**Comment by snipe** [comment]
Also can we instead say "Go to <asset tag>" instead of the model name? 
And drop a cookie so we remember your choice?

Should this be in v6 or v7? Seems like a v7 feature.

**Comment by Godmartinz** [comment]
> Also can we instead say "Go to " instead of the model name? And drop a cookie so we remember your choice?

There is a session variable that remembers 1 of your 3 choices. The "Go to model" is a choice in itself, if you wanted to go to the asset you are checking out every time.

**Comment by Godmartinz** [comment]
Added a test for the get redirect options. Going to add some more clarity into the option selected values.

**Pull request merged**
