### PR TITLE
Fixed Ldap sync field clear bug

### LINKED ISSUE #13373: LDAP wipes data of non set AD attributes on sync
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If we don’t put a value, for example in the snipe department LDAP setting, then the data of departments gets wiped in the snipe database after an LDAP sync.

### Reproduction steps

1. Let the department value empty in the snipe LDAP settings
2. Assign a department to a snipe user
3. Do a LDAP sync
...

### Expected behavior

The department value should not be removed. Only when a value is set in the LDAP department settings and there is no department value in the AD should the department value in the snipe database be deleted/overwritten.

### Screenshots

_No response_

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu Server 20.04

### Web Server

Apache/2.4.41

### PHP Version

8.1.20

### Operating System

Windows 

### Browser

Google Chrome

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

```shell
None
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
If an LDAP settings field was left blank for a sync it would null the existing users' matching fields. This applies a check on the ldap settings options itself. 

Fixes #13373 

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Thanks for this :) Two quick things - looks like we have a merge conflict here - can you handle that? Second, is it a possible scenario that we'd end up with a blank value vs null?

**Comment by snipe** [comment]
Ping @Godmartinz

**Comment by Godmartinz** [comment]
Ah! sorry, Conflicts are fixed. You brought up a good point about blank space. there shouldn't be any spaces allowed, before, in between, or after. going to add some validation for this in another PR against the livewire changes.

**Comment by Godmartinz** [comment]
@snipe as mentioned in the dev meet yesterday, i posted a separate PR that trims whitespace off an values for the ldap attributes. You _could_ technically put a blank in for any field, but it would not sync anything if you did.

**Pull request merged**
