### PR TITLE
Added #542: add saml authentication

### PR DESCRIPTION
**Pull request by johnson-yi**
I have implemented SAML authentication support into Snipe-IT.

saml_settings

You can easily test by using the [metadata](https://johnson-yi.github.io/samling/public/metadata.xml) of my fork of Samling (Serverless IdP) and entering in the Name Identifier field the username of an existing user.

samling

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks so much for this. Has it been tested with non-Samling SAML integrations? (My fear here is that we're going to get slammed with a ton of support requests we may not be able to handle, supporting systems we can't introspect into.)

**Comment by johnson-yi** [comment]
Hi Snipe - Samling is just a tool for emulating an IdP and sending SAML messages. I have been using it for development to test, check and debug.

I have tested my implementation with ADFS and Shibboleth. There is a public testing IdP samltest.id based on Shibboleth that it works with.

The SAML authentication is handled by [onelogin/php-saml](https://github.com/onelogin/php-saml) library. I have customised and designed it to fit into Snipe-IT.

SAML errors from the library are sent to LOG::debug 

when_saml_error
bad_idp
saml_debug_bar

**Comment by johnson-yi** [comment]
I have further tested SAML authentication against OneLogin & JumpCloud and can confirm that it works correctly.

**Comment by snipe** [comment]
Thanks so much for the clarification. This is HUGE. We're really focused on trying to ship v5 right now (and solving the last remaining blocker issues), so we weren't even looking at SAML integration until those bits were handled.

**Comment by pitbulk** [comment]
@johnson-yi nice work!

**Comment by queryluke** [comment]
FYI - I've tested this with AzureAD at it works perfectly.

Thanks so much @johnson-yi !!!

**Comment by srikanth-prem** [comment]
@johnson-yi  Thank you for this. Just as I was looking for SAML support I found this.

Could you please let us know when this be getting released?

**Comment by ajf15cc** [comment]
Hi - Is there any idea when this will come in to a stable release?

**Comment by viclou** [comment]
@johnson-yi @queryluke any instructions/documentation you can share on using the new SAML Authentication would be GREATLY appreciated! I'd love to get together general settings for each AzureAD, Jumpcloud, OneLogin, ADFS and Shibboleth and any others : )

**Comment by queryluke** [comment]
@viclou 

I've only set this up with AzureAD. It was incredibly simple.

### Step 1: Metadata File (optional)
1. In Snipe-IT, go to __Admin__ > __SAML Settings__. 
2. Check __SAML Enabled__ and click "Save". 
3. A metadata URL will appear just below the __SAML Enabled__ checkbox.
4. Click on the URL (opens a new tab)
5. In the new tab, save the file (Cmd+S or Ctrl+S). Note it's location.

### Step 2: Create App in Azure AD
In Azure AD, you create a new enterprise application: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal

### Step 3: Setup SSO in Azure AD
Then you configure SSO for the newly created app: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal-setup-sso

When setting this up, you can upload the metadata file from step 1. Alternatively, you can add the following fields. Note, this method may not work if you have customized your SAML settings within Snipe-IT. It is safer to use the metadata file.
**Identifier URL**: This is the url to the Snipe-IT instance
**Reply URL**: The identifier URL with `/saml/acs` appended

Also Note, in the guide from Microsoft that I've linked, they indicate that Sign-in URL is required, but I have not found that to be the case.

Here is a screenshot of our config in Azure AD:
azure-ad-settings

### Step 4: Copy Azure AD's metadata URL
With Azure AD set up, copy the __App Federation Metadata Url__ from the __SAML Signing Certificate__ section.

### Step 5: Add AzureAD's metadata URL to Snipe-IT
Within Snipe-IT, paste Azure AD's metadata URL into the __SAML IdP Metadata__ textarea. Click save.

Here is a screenshot of our complete Snipe-IT SAML Settings:
snipe-it-settings

That should be it! Let me know if you need any clarifications.



<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal">Quickstart: Add an application to your Azure Active Directory (Azure AD) tenant</a></strong></div><div>This quickstart uses the Azure portal to add a gallery application to your Azure Active Directory (Azure AD) tenant.</div></blockquote>
<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal-setup-sso">Quickstart: Set up SAML-based single sign-on (SSO) for an application in your Azure Active Directory (Azure AD) tenant</a></strong></div><div>This quickstart walks through the process of setting up SAML-based single sign-on (SSO) for an application in your Azure Active Directory (Azure AD) tenant.</div></blockquote>

**Comment by viclou** [comment]
thanks @queryluke!

**Pull request merged**
