### PR TITLE
Improved Asset Search: use zerofill for searchbar

### PR DESCRIPTION
**Pull request by julian-piehl**
I updated the Asset:getAssetByTag Method to use zerofill.
Now you don't have to write the whole AssetTag, only the short version.

**Example**
Before: 000000001
Now: 1

### CODE REVIEW

**Comment by snipe** [comment]
I’m not sure this is a good idea tho. The whole point of zero-filling is that 00000123 and 123 are not necessarily the same.

**Comment by snipe** [comment]
The top search does an exact search, not a fuzzy search for a reason.

**Comment by david7867z** [comment]
Then why not make it a setting for the enduser?
You dont want people having to write "0000000009" when you dont have a barcode reader at hand.
Yes. They are not necessarily the same, but they can absolutely be!

**Comment by snipe** [comment]
Top search is optimized for barcode scanners. Every extra setting has a cost - in testing, in everything else.

**Pull request closed without merging**
