### PR TITLE
Receiving hot fix

### PR DESCRIPTION
**Pull request by DarthKillian**
# Description

Fixes semi colon showing up on the receiving page

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by DarthKillian** [comment]
Created PR for this repo instead of mine because I was rushing. SOOOO sorry for wasting anyone's time. :(

**Comment by snipe** [comment]
Defect creation time to defect correction time was *one* minute - you're fine :)

**Comment by DarthKillian** [comment]
Sweet! Btw, I sent an email to you last week that I figured out a "solution" to. I'd like to pick your brain though on running tests if you'd have any time. I'm having issues with getting it to work and I'm sure it's just me doing something wrong. I'm trying to learn to do testing and be a kosher coder to eventually contribute to this project.

**Comment by snipe** [comment]
@DarthKillian I don't recall seeing an email from you? What email address did you send to? (I'm also VERY BAD at email, so I might have just missed it.)

@marcusmoore has been working on getting our tests back up to par, so keep an eye out for PRs from him related to that. I know he's made some recent updates to our [testing readme](https://github.com/snipe/snipe-it/blob/master/TESTING.md).

**Comment by snipe** [comment]
We also have a [discord channel for testing](https://discord.com/channels/849770616521359401/916046592220495882), though I don't think Marcus is in there often, but I'd bet we could convince @svpernova09 to help out where he can. :)

**Comment by DarthKillian** [comment]
@snipe It's an email that I can't disclose publicly due to my privacy. But I emailed you towards the end of the year thanking you about the project and you responded in January of 2023. If you're on Discord, I can DM you there if you'd prefer. I just want to also be respectful of your time. There's also kinda a golden rule to not just DM devs/owners a lot of places.

**Pull request closed without merging**
