### PR TITLE
Nicer formatting of the page if custom logout [ch15660]

### PR DESCRIPTION
**Pull request by Godmartinz**
centered and increased the font of the ldap password reset link
[](url)
Screen Shot 2021-02-01 at 4 52 12 PM

Could be more shiny? Thoughts?

### CODE REVIEW

**Comment by snipe** [comment]
This looks good, thanks! Can you show me a screen shot of what this looks like if you have a logo uploaded as well? (Just want to make sure the spacing looks okay under the logo image.)

I might want a little more padding at the top of that div, and we may want to skip using the `box-header` class, since CSS-wise, it's not really a header (which implies there would be a `box-body` or something else happening there.) This looks pretty close though.

**Comment by Godmartinz** [comment]
Screen Shot 2021-02-01 at 5 23 17 PM

This is what it looks like currently

**Comment by snipe** [comment]
Perfect, thanks - can you give me 20 more pixels of padding at the top of that box so it's not so squished against the top of the page if there isn't a logo? 

(Also I'm not sure how, but this PR is showing conflicts - we should probably figure out what's up with that. )

**Review by snipe — CHANGES_REQUESTED** [review]
Can you give me 20 more pixels of padding at the top of that box so it's not so squished against the top of the page if there isn't a logo?

(Also I'm not sure how, but this PR is showing conflicts - we should probably figure out what's up with that. )

**Comment by Godmartinz** [comment]
closing this pull request, will reopen a new one.

**Pull request closed without merging**
