### PR TITLE
Added `purchase_cost` to user's default view [sc-19680]

### PR DESCRIPTION
**Pull request by inietov**
# Description
A picture says more than a thousand words.

image

Fixes shortcut 19680

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by brianhoganm** [comment]
Can we have the option to enable or disable this? I DONT WANT PEOPLE TO
KNOW THE COST.

**Comment by snipe** [comment]
TY for this, @inietov! How do we handle it if a company doesn't want that purchase price surfaced though? We withheld it from that view because most companies don't need or want employees seeing that cost.

**Comment by snipe** [comment]
@brianhoganm we discussed this during the standup today. I think we’ll likely add this into the permissions screens in the user and group permissions, defaulting to “deny”.

**Comment by inietov** [comment]
@snipe I add the permission for assets' purchase costs. Accessories and Consumables are not in the scope because I'm not sure if I should wrap those columns in my permission because those columns were already shown before my changes were pushed.

**Comment by snipe** [comment]
@inietov Per our discussion today, I think it's okay if we wrap those into the "Self:" permissions. It would be odd (IMHO) to also people to see the price of one thing but not other things. (I am willing to hear use-cases that prove me wring tho.)

**Comment by snipe** [comment]
Beautiful, thanks!

**Pull request merged**
