### PR TITLE
Fixed #14091 : Update Dockerfile.alpine to correct the logs folder rights

### LINKED ISSUE #14091: Incorrect right for log folder in docker-compose
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

With the default docker-compose installation, the logs folder is not owned by apache:apache and it causes a permission error. during the installation setup. 

```
# ls -al
total 44
drwxrwxr-x    1 apache   apache        4096 Jan  3 20:47 .
drwxr-xr-x    1 apache   apache        4096 Jan  3 20:47 ..
drwxrwxr-x    1 apache   apache        4096 Jan  3 20:47 app
drwxrwxr-x    1 apache   apache        4096 Dec 24 20:14 debugbar
drwxrwxr-x    1 apache   apache        4096 Dec 24 20:14 framework
drwxrwxr-x    2 1000   1000          4096 Dec 24 20:14 logs
lrwxrwxrwx    1 apache   root            39 Jan  3 20:47 oauth-private.key -> /var/lib/snipeit/keys/oauth-private.key
lrwxrwxrwx    1 apache   root            38 Jan  3 20:47 oauth-public.key -> /var/lib/snipeit/keys/oauth-public.key
lrwxrwxrwx    1 apache   root            37 Jan  3 20:47 private_uploads -> /var/lib/snipeit/data/private_uploads

``` 

In ordre to fix the issue, I added one line in the Docker.alpine file : 

```
RUN chown -hR apache:apache /var/www/html/storage/logs

``` 

### Reproduction steps

please see bug report, everything is there

### Expected behavior

please see bug report, everything is there

### Screenshots

https://github.com/snipe/snipe-it/blob/master/docker-compose.yml

### Snipe-IT Version

Current docker-compose.yaml file

### Operating System

Ubuntu 22.04

### Web Server

docker-compose // alpine

### PHP Version

no idea, but that is not relevant to the issue

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Decode1415**
Add

RUN chown -hR apache:apache /var/www/html/storage/logs

to Dockerfile.alpine to have the proper right for the logs folder.

# Description

Related to issue 
https://github.com/snipe/snipe-it/issues/14091

### CODE REVIEW

**Comment by snipe** [comment]
Almost there - this needs to be targeted to the `develop` branch, [per the dev documentation](https://snipe-it.readme.io/docs/contributing-overview) :)

**Comment by snipe** [comment]
Heh, welcome to the hell that is git. It looks like it's going to need a rebase. If you look at Files Changed in this PR UI, it shows 44 files changed, and I know you didn't change 44 files. That's likely because you branched off of master, we made a bunch of changes, then you retargeted, so your PR is picking up our changes that happened since you first forked the repo. 

I also understand if this is getting to be too much hassle, so if you want me to just add your changes, I can do that :) 

You can:

1) Do a fresh pull from the develop branch and re-apply your changes
2) Rebase 
3) Ask me to just apply your changes

Any of these will work, just let me know what you'd like to do :) We appreciate the contribution, whichever way you go. (I don't normally offer to "just do it", but it's a one-liner, so it's easy enough on our end - now it just depends if you want to learn a little more about git and Github workflows, or if you just want it handled.)

**Review by uberbrady — CHANGES_REQUESTED** [review]
Can we get a change with just this `chown` line, and leaving the `config/version.php` file and built assets alone? Still targeting the `develop` branch, please. Then we can accept that and get it pushed into the `Dockerfile`. Thank you!

**Comment by Decode1415** [comment]
@uberbrady 
Sorry, but I do not understand. I did modify the file `config/version.php` ?

**Comment by snipe** [comment]
@Decode1415 No, the problem is that when you retarget and your version of develop is behind ours, it picks up a bunch of our changes. Notice it says 44 files changed still? You'd need to rebase or close this PR and open a new one with JUST your change based from the develop branch, and then open a PR against the develop branch.

**Pull request closed without merging**
