### PR TITLE
Fixed #11179: APP_FORCE_TLS is missing from the example .env.docker

### LINKED ISSUE #11179: Https ui broken in Docker/Kubernetes
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

working with argocd (k8s) and nginx-controller, the domain name on aws route53 as same as the certificate.

When I open the ui as http request it is works fine but with the https the ui is broken, like it doesn't read the css files.

any ideas?

### Reproduction steps

1. added a certificate at aws acm
2. annotated it to nginx controller
3. open the web at https://my.domain.snipe and the ui is broken
...

### Expected behavior

To see the page (as normal) as the http shows me.

### Screenshots

Screenshot from 2022-05-23 05-52-02

### Snipe-IT Version

6.0.0

### Operating System

helm k8s alpine

### Web Server

n/a

### PHP Version

PHP 7.4.3 

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

```shell
No errors...
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mmanjos**
# Description

Was trying to bring up a docker hosted instance behind TLS and had issues with plaintext CSS resources not loading in chrome. I came across https://github.com/snipe/snipe-it/issues/2090 which suggested that `APP_FORCE_TLS` is now needed. 

I believe it should be present in the example `.env.docker` file

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by snipe** [comment]
Good catch, thanks!

**Comment by snipe** [comment]
Can you retarget this to develop though, per the developer docs?

**Comment by mmanjos** [comment]
Will do! (in about 1 hour)

**Comment by mmanjos** [comment]
rebasing to `develop`

**Pull request closed without merging**
