### PR TITLE
Changes Google Map to be a bit more detailed

### LINKED ISSUE #8465: Adjust Google Maps zoom
**Server (please complete the following information):**
 - Snipe-IT Version: 4.9.5
 - OS: Windows Server 2019
 - Web Server: IIS
 - PHP Version: 7.3.20

**Is your feature request related to a problem? Please describe.**
Our company has multiple locations set up, however they're all in the same city. The Google Maps tile is all the same for each location.

**Describe the solution you'd like**
An option (so companies that don't want to go that detailed) to include the full address in the Google Maps query makes the tile unique.

### PR DESCRIPTION
**Pull request by benwa**
# Description
This makes the Google Maps tile a bit more detailed for addresses.

Fixes #8465: Adjust Google Maps zoom

## Type of change
- [x] New feature (non-breaking change which adds functionality)
image

# How Has This Been Tested?
Modified on a local install. Map continues to work if address line 1 is or is not filled out.

**Test Configuration**:
* PHP version: 7.3.20
* MySQL version: MariaDB 10.1
* Webserver version: IIS 10
* OS version: Windows Server 2019

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Hi, thanks for this! Have you tested how this acts when there is no address? 

(Also, please, per the docs, all PRs should be targeted to develop. We're about to release v5 this week, so ....)

**Comment by benwa** [comment]
I did test when the address is blank, it works as expected.
I'll try to retarget to develop (might take me a bit, not sure how to do
that on the top of my head).
Congrats on v5!

**Comment by snipe** [comment]
Funnily, I have a canned response for that :D 


Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by snipe** [comment]
If it ends up being a giant shit-show, lemme know and I'll just apply your changes. Just trying to juggle a lot right now, so if it's easy, do it. If it's going to take more than 30 minutes of your time, I'll just pull those changes over and give you credit in the changelog.

**Comment by benwa** [comment]
Awesome, that was very helpful. Thank your again for this great project!

**Comment by snipe** [comment]
Perfect, thanks! <3

**Pull request merged**
