### PR TITLE
Fixed #13446 - added translations to status label type column

### LINKED ISSUE #13446: [Feature Request]: Translation on page status labels not finished
### Is your feature request related to a problem? Please describe.

On the page "Status Labels" in the table the text of the "Status Type" is not translated.

English:
image

German:
image

### Describe the solution you'd like

The status type in the table should also be translated.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

Updates the `statusLabelTypeFormatter` with a translation variable for the `status_type` column in the table.

image
image

Fixes #13446

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
This is going to hitch us up in the API I think.

https://github.com/snipe/snipe-it/blob/ec2556f9914222be9536e3b46a987d8e8c74657d/app/Http/Controllers/Api/AssetsController.php#L516-L518

**Comment by Godmartinz** [comment]
@snipe  I rethought it and fixed it through the table formatter instead of the model.

**Comment by snipe** [comment]
Nice!

**Comment by floschoepfer** [comment]
Hey @Godmartinz thanks for this!
I just noticed, that the status "deployable" now has a red circle as icon instead of a red cross. I like that, since the status "archived" already uses a red cross.

But could you please add the icon also to the "About Status Labels" descriptions, so it is consistent?
image

**Pull request merged**
