### PR TITLE
Fixed #13094: Update Depreciable.php

### LINKED ISSUE #13094: Incorrect Calculation for Half Year Depreciation Model
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

<@821841663718326283> 
On Asset screen, assets with half year depreciation method set are not showing current value, but instead they are showing the amount that has depreciated. For example for a $1000 asset, it is showing Current value as $125 instead of $875.

### Reproduction steps

1. Set Depreciation to Half Year
2. Navigate to Asset Screen
3. Check Value listed for Current Value

### Expected behavior

$1000 Original Purchase Price with 4 year depreciation and floor value of $0
7 months after purchase, Current value should reflect $875, but instead the value reflected is $125, which is the depreciated amount.

### Screenshots

_No response_

### Snipe-IT Version

6.1.1

### Operating System

Docker Container

### Web Server

Docker Container

### PHP Version

Docker Container

### Operating System

Windows

### Browser

Edge

### Version

113.0.1774.50

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

I was able to resolve the issue on my machine by modifying line 130 of Depreciable.php

**Original**
`return round($yearsPast / $deprecationYears * $this->purchase_cost, 2);`

**After Modifying**
`return $this->purchase_cost - round($yearsPast / $deprecationYears * $this->purchase_cost, 2);`

### PR DESCRIPTION
**Pull request by jdickerson71388**
# Description

On Asset screen, assets with half year depreciation method set are not showing current value, but instead they are showing the amount that has depreciated. For example for a $1000 asset, it is showing Current value as $125 instead of $875.

This change will fix that calculation.

Fixes # 13094

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Modified the necessary files in my setup and verified that the depreciation calculation is correct on multiple items

**Test Configuration**: Docker Container

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Godmartinz — APPROVED** [review]

**Comment by snipe** [comment]
Hi - can you please retarget to develop, per the developer documentation?

**Comment by jdickerson71388** [comment]
> Hi - can you please retarget to develop, per the developer documentation?

Done. Thank you!

**Comment by snipe** [comment]
Dangit - looks like we gave merge conflicts now.

**Comment by snipe** [comment]
(Also 43 changed files seems like a lot? Might need a rebase here?)

**Review by uberbrady — CHANGES_REQUESTED** [review]
Can we have this re-targeted to 'develop'  - without the extraneous changes, please? Then we'll take it - all of the other depreciation methods work pretty much the same way - purchase cost minus the depreciated value, so I assume this one should work the same too.

**Pull request closed without merging**
