### PR TITLE
Added devcontainer

### PR DESCRIPTION
**Pull request by clouddevopsworks**
devcontainer.json file will create the devcontainer. source code will be mapped in the /var/www/html inside the devcontainer and developer can immediately do the code changes and check.

### CODE REVIEW

**Comment by svpernova09** [comment]
This seems to work well enough. I'd probably prefer to revert your change to `.env.docker`. Seems dangerous to run a "devcontainer" in "production" :D



```
Running .docker migration
Migration: no config.json detected
Migration: no .docker/docker-compose.yaml detected
Downloading tool to detect main repo language...
Done downloading.
Detecting main repo language...
Unsupported language "PHP" - using default base image
app Pulling 
...
Network snipe-devcontainer-pr_default  Creating
Network snipe-devcontainer-pr_default  Created
Container snipe-devcontainer-pr-app-1  Creating
Container snipe-devcontainer-pr-app-1  Created
Container snipe-devcontainer-pr-app-1  Starting
Container snipe-devcontainer-pr-app-1  Started

```

We might need more configuration here, as there aren't any ports being forwarded, apparently the devcontainer isn't respecting ports shared in the docker-compose.yml, which seems odd. But even using the `forwardedPorts:` configuration I still wasn't able to get it to share ports.

```
"forwardPorts": [
    [8080, "snipeit:80"]
],
```

image

**Review by snipe — CHANGES_REQUESTED** [review]
[svpernova09](https://github.com/svpernova09) has some changes he wanted to see - can you address those or close this PR? Thanks!

**Comment by snipe** [comment]
Also this should be targeted to `develop`, per our developer docs. :)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this for now, but will re-open it if you're still having issues.

hackerman-hacking

**Pull request closed without merging**
