### PR TITLE
Fixes a couple blade templates for relative URLs

### PR DESCRIPTION
**Pull request by joelpittet**
# Problem/Motivation

On 5.x release, most of these were fixed (had a PR ready to go). These are just the stragglers.
Makes sure our site (which are in sub directories) have the correct base URL on assets.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by joelpittet** [comment]
My apologies for the whitespace changes in the file, didn't realize that until after the PR, LMK if I should remove them?

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by snipe** [comment]
(No worries about the whitespace changes - it's only two files.)

**Comment by joelpittet** [comment]
Ah thanks, sorry, not a big docs reader until I'm in trouble... `develop` it is!

**Review by snipe — CHANGES_REQUESTED** [review]
Can you do a quick rebase here? I'm seeing 37 files changed, and I suspect that's not true in this case. :D I'd love to merge your stuff in if you can bang that out real quick. <3

**Comment by snipe** [comment]
Perfect, thanks!

**Comment by joelpittet** [comment]
I was going to force push a single nice commit but that would have closed the PR again... great thanks for merging! Friday seems to be the day 🍸

**Pull request merged**
