### PR TITLE
Docker fpm nginx

### PR DESCRIPTION
**Pull request by Virtute90**
# Description

Hello everybody,
thanks for your contribution, you have built a really fantastic tool.

Taking a cue from this issue [https://github.com/snipe/snipe-it/issues/9313](https://github.com/snipe/snipe-it/issues/9313) I modified and adjusted the files to create a custom docker image in FPM-Alpine mode with php v8.1, nginx webserver, mysql v8 database and redis v7 server.
I also wrote a little guide to help build the image.

This is the pre-flight page:

image

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Docker Desktop on Windows 10
- [ ] Ubuntu server 22.04.1

**Test Configuration**:
* PHP version: 8.1
* MySQL version: 8
* Webserver version; Nginx 1.23

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
This looks great - thanks so much!

**Comment by snipe** [comment]
(Next time if you can, please put PRs against develop)

**Comment by snipe** [comment]
Actually, if you can re-apply these to develop instead of master, that would be great. I tried switching branches and I think you're a little behind on your fork. It went from 7 changed files to 49 :( Can you do a quick pull/rebase and put this towards develop?

This looks like a great, clean PR, and I love the documentation.

**Comment by Virtute90** [comment]
> Actually, if you can re-apply these to develop instead of master, that would be great. I tried switching branches and I think you're a little behind on your fork. It went from 7 changed files to 49 :( Can you do a quick pull/rebase and put this towards develop?
> 
> This looks like a great, clean PR, and I love the documentation.

Thanks for the answer Snipe!

I tried to change the branch to develop but now 280,000 fewer rows appear, I think there is something wrong.

At this point I will fork the develp, as you indicated, and recreate the pull.

This can be closed.

**Comment by Virtute90** [comment]
I'll do the pull again in a couple of days!

Thank you

**Comment by snipe** [comment]
Awesome, thanks! This looks like a solid PR, and I'm excited to take it when it's ready.

**Comment by Virtute90** [comment]
> Awesome, thanks! This looks like a solid PR, and I'm excited to take it when it's ready.

For being the first PR, you give me too many compliments!

**Comment by snipe** [comment]
I can stop if you want :P

**Pull request closed without merging**
