### PR TITLE
Add Import data tests

### PR DESCRIPTION
**Pull request by bryanlopezinc**
# Description

Added tests for importing assets, accessories, consumables, users and licenses.

**Test Configuration**:
* PHP version: 8.1, 8.2
* MySQL version: 8.1

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by snipe — CHANGES_REQUESTED** [review]
These tests seem to be failing? The `groups` table was renamed to `permission_groups` several years ago.

**Comment by marcusmoore** [comment]
These test failures seem to be similar to the ones in [this PR](https://github.com/snipe/snipe-it/pull/15533)...in this PR the failing tests are in an unrelated test, `Tests\Feature\Users\Api\UpdateUserTest`, and that test doesn't fail in isolation, only when the entire suite is run...just like [this PR](https://github.com/snipe/snipe-it/pull/15533).

@bryanlopezinc thank you for this effort. I'm going to work on fixing the tests in the other PR and hopefully a fix there will include a fix here.

**Comment by bryanlopezinc** [comment]
@marcusmoore it is indeed a tricky bug. can you check out this fix https://github.com/snipe/snipe-it/pull/15602

**Comment by marcusmoore** [comment]
Ah! I figured it out late yesterday and was going to write a comment about it this morning. I'll open a PR with a deeper level fix in a bit.

**Comment by marcusmoore** [comment]
@bryanlopezinc I think the broken tests will be handled with #15603.

I'm going to assume that is the case and give this a proper review later today 👍🏾

**Comment by marcusmoore** [comment]
@bryanlopezinc thank you so much for these tests. The importer is a core feature and you beat me to writing tests around it 😄 . 

The foundation of this PR is **solid** but there are some changes I want to make before a full merge. I'm going to merge it to a temporary branch and open another PR with my changes/additions on top of it. 

(Of course you'll still get the credit for your commits to the project)

**Comment by bryanlopezinc** [comment]
@marcusmoore great! Feel free to modify them.

**Pull request merged**
