### PR TITLE
Fixed #NA: typo

### PR DESCRIPTION
**Pull request by reederda**
# Description

Fixed a typo on the front page of a fresh install ("haven not" to "have not")

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
- Ran a grep to search for affected string after applying fix, found no further issue

### CODE REVIEW

**Comment by snipe** [comment]
Hey, thanks for this - good catch! Can you revise this PR to only deal with the English language translation? 

We don't currently manage translations through Pull Requests however, only through the CrowdIn platform. You can find more info on that here: https://snipe-it.readme.io/docs/translations

<blockquote><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>

**Comment by mikeroq** [comment]
> Hey, thanks for this - good catch! Can you revise this PR to only deal with the English language translation?
> 
> We don't currently manage translations through Pull Requests however, only through the CrowdIn platform. You can find more info on that here: https://snipe-it.readme.io/docs/translations
> 
> > Snipe-IT Documentation**[Translations](https://snipe-it.readme.io/docs/translations)**Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!

Off topic, but on topic, what about translations that don't exist yet? I know I've seen various places where it's still english directly in the blade/etc.

Or where there is a trans() in the blade/etc but there is no corresponding key in the language files? (Like during the setup wizard, especially on the migrations page).

Thanks!

<blockquote><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>

**Comment by snipe** [comment]
> Off topic, but on topic, what about translations that don't exist yet? I know I've seen various places where it's still english directly in the blade/etc.

We've tackled a lot of those already, but they should be extracted out into strings.

> Or where there is a trans() in the blade/etc but there is no corresponding key in the language files? (Like during the setup wizard, especially on the migrations page).

That issue was already fixed IIRC.

**Comment by mikeroq** [comment]
> > Off topic, but on topic, what about translations that don't exist yet? I know I've seen various places where it's still english directly in the blade/etc.
> 
> We've tackled a lot of those already, but they should be extracted out into strings.
> 
> > Or where there is a trans() in the blade/etc but there is no corresponding key in the language files? (Like during the setup wizard, especially on the migrations page).
> 
> That issue was already fixed IIRC.

For lack of better place:
image
(Also the page title)
Same on current master/develop.

**Comment by karoliskralis** [comment]
When i want to edit asset model i get HTTP 500 error after instaling new versio
error
n

**Pull request merged**
