### PR TITLE
Starter Livewire config (for subdirectories)

### PR DESCRIPTION
**Pull request by snipe**
Possible fix for #11195

### CODE REVIEW

**Review by uberbrady — APPROVED** [review]
Yeah, something along this line is what I was thinking. The only concern I have is whether or not Livewire can properly parse a fully-qualified URL, rather than the 'pathname' that it's alleged to want. But if it'll take it, and it works, then I'm happy to sign off.

**Comment by snipe** [comment]
The example they use is:

```
/*
    |--------------------------------------------------------------------------
    | Livewire Assets URL
    |--------------------------------------------------------------------------
    |
    | This value sets the path to Livewire JavaScript assets, for cases where
    | your app's domain root is not the correct path. By default, Livewire
    | will load its JavaScript assets from the app's "relative root".
    |
    | Examples: "/assets", "myurl.com/app".
    |
    */
```

While it doesn't include the protocol, I wouldn't *think* it would be an issue? Perhaps @bobeagan can give this branch a test in his subdirectory setup?

**Comment by bobeagan** [comment]
Since my config file is untracked, I figure I can just change the hardcoded `/inventory` string to `env('APP_URL')` and then run `php artisan config:cache` to see how it goes. Assuming that's the only difference between this PR and my existing file, which at a cursory glance seems to be the case, this does appear to also load the file just fine. Inspecting the script tag and it shows the script source with the full domain and protocol in there (where it was only a path previously).  Seems to get a 👍 from me for working with using the env var.

**Comment by snipe** [comment]
@bobeagan Awesome, thanks so much for testing :)

**Pull request merged**
