### PR TITLE
Fixed #12655 - Adds translations for category types to index and edit of categories

### LINKED ISSUE #12655: Incorrect language switching
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Incorrect switching language.

### Reproduction steps

We have CentOS 9, Apache v.  2.4.53, Snipe-IT v. 6.0.14 wich was intalled with script.
After that i switched language in env file and in users profile from English to Russian. I noticed the following error:
On the main page sections of Assets,  Accessories, License and Consumable display correctly in Russian, but if i want to create Categories in section "Type of Categories" I see that the specified categories are not translated into Russian.

### Expected behavior

What i should do to fix that proplem?

### Screenshots

Screenshot_20230312_133619
Screenshot_20230312_133640
Screenshot_20230312_133647

### Snipe-IT Version

6.0.14

### Operating System

CentOS

### Web Server

Apache

### PHP Version

8.0.20

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
Puts translations into the index and editing of categories so localization will reflect now appropriately.

image
image

 Before pictures in the issue mentioned below
Fixes #12655 

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by snipe — CHANGES_REQUESTED** [review]
I don't think this is going to work as expected here. The `category_type` is a "magical" incantation that the database uses, so the value stored in the database has a finite set of values. If we translate this and store the translations instead of the English phrase, we could end up with very unpredictable data. For example, if an admin had Snipe-IT in Portuguese first, did a bunch of category creation (where `category_type` is set), we'd end up storing those types as Portuguese phrases - then they switch it to English and we won't be able to recognize that type anymore.

**Comment by snipe** [comment]
(Also remember that one install can support multiple languages - i.e. staff based across the world where they have their profiles localized in their native tongue. Those `category_types` would break there as well.

**Comment by Godmartinz** [comment]
im not really following @snipe,  the `category_types` are static values that were hardcoded in English. I just put a translation there. The `categoryType()` function changes statically as well. How should I go about this? 🤔

**Comment by MikServ** [comment]
@Godmartinz Can you remove the categories after changing the Helper.php andCategoriesTransformer.php?
I have some problem. After changing these files i can`t delete any categories.

**Comment by Godmartinz** [comment]
double checked the database and it is saving correctly still 👍 
image

**Comment by snipe** [comment]
Looks like we're using a plural here for accessories. I'll fix it.

**Pull request merged**
