### PR TITLE
Bug/ch16128/mobile web app broken left hand menu cannot

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
Fixes positioning errors on the desktop with the sidebar being behind other elements of the page when not in fullscreen:
image

Also fixes a similar issue when using a mobile device that the Nav and header would block the sidebar menu tree:
image

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, providing screenshots where practical. List any dependencies that are required for this change.

Fixes # (issue)
#9667 [ch16128] [ch17130]

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by snipe — CHANGES_REQUESTED** [review]
We don't make changes directly to sidebar.less or sidebar-mini.less, since they are core parts of AdminLTE. We'd move those changes to app.less or overrides.less, which is all of our customizations are (I just forget which order they load in, so not sure which would be the appropriate one to use here.)

**Comment by Godmartinz** [comment]
Got it, I have removed those changes.

**Comment by Godmartinz** [comment]
This is still open, Is there something else I need to correct or add here? @snipe

**Comment by snipe** [comment]
Can you do a fresh pull and/or rebase to get these merge conflicts handled?

**Pull request closed without merging**
