### PR TITLE
Basic encrypted custom fields support for checkboxes - needs testing, tests, and love

### PR DESCRIPTION
**Pull request by uberbrady**
Sometimes some customers might choose to encrypt custom fields that are just a collection of checkboxes. We should be able to support that.

### CODE REVIEW

**Comment by spencerrlongg** [comment]
@uberbrady I got some initial tests for non-encrypted checkbox testing, and found a problem on the first test I started writing for encrypted checkbox. There's a note in the validator about it. From memory, this is the problem I had when I was writing this validator initially and why I started questioning the encrypted checkbox in the first place. 

From what I remember, I was having problems consistently decrypting `$options` to get things to a place where I could do the array comparison for the validation. 

I stopped when I remembered I couldn't really test it without going and re-enabling the feature on the front end to get an encrypted checkbox set up, so I'll get back to that in the morning. Or maybe later tonight if I can't sleep again.

**Comment by uberbrady** [comment]
Thank you for the tests! Let me see if there's anything I can help with.

**Comment by spencerrlongg** [comment]
DONT MERGE

Found a pretty significant issue with this that needs attention first. We can talk on Monday.

**Comment by spencerrlongg** [comment]
Alright, I think that was a false alarm, sorry - I was trying to check an asset out and was failing encrypted checkbox validation, but that's actually happening on dev, not this branch. 

Seems like a backwards-compatibility issue if I've set encrypted checkbox data and switch back to dev - which makes sense.

**Comment by snipe** [comment]
Probably slightly related to this: https://github.com/snipe/snipe-it/issues/14720

Tho based on internal conversations, the encryption part isn't really the issue here 😬 )

**Pull request closed without merging**
