### PR TITLE
Fixed Component Factory: use manufacturer factory for `manufactuer_id`

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

title says it all.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
I specifically chose not to use that factory, since the Manufacturer seeder runs before the components seeder, and I wanted to have potentially more than one component per category. The seeders are not realistic when we create a brand new manufacturer for each item.

**Comment by Godmartinz** [comment]
oh ok, there was like 20 something failing tests, thats why I changed it. Ill close for now then.

**Comment by snipe** [comment]
What were the failing tests? They worked when I ran them locally

**Comment by marcusmoore** [comment]
[This commit](https://github.com/snipe/snipe-it/commit/a9eea830e30f75a4b46648d3bf99d9aa54f07c99) triggered [these failures](https://github.com/snipe/snipe-it/actions/runs/11485600856/job/31966058483).

**Comment by snipe** [comment]
I’ll take a look - thanks for the heads up

**Comment by snipe** [comment]
That failure doesn't even make sense here tho. Notifications were not modified at all.

**Comment by marcusmoore** [comment]
There are a bunch of tests around components failing. I think they're not able to be created. There's a lot of "trying to call x on null".

**Comment by snipe** [comment]
Yeah, I see that too, but manufacturer isn't required, it just has to exist (which it should, since the Manufacturer seeder runs before the Components seeder)

```
'manufacturer_id'   => 'integer|exists:manufacturers,id|nullable',
```

**Comment by marcusmoore** [comment]
Seeders aren't run during tests though. I'm diving in to double-check I'm not mistaken.

**Comment by snipe** [comment]
Null manufacturer for tests should still work fine too tho, per the validation.

**Comment by marcusmoore** [comment]
But it's not set to null...the factory is setting it to a random int between 1 and 5 and a manufacturer doesn't exist for that id.

**Comment by snipe** [comment]
Right - there has to be a better way tho. One new manufacturer per component in the seeders is crap seed data.

**Comment by snipe** [comment]
(@Godmartinz - can you retarget this to develop please.)

**Comment by marcusmoore** [comment]
The Component factory is (silently) failing to actually create a model when `'manufacturer_id' => $this->faker->numberBetween(1, 5)` is in the factory definition:
CleanShot 2024-10-23 at 17 09 43@2x

Interesting that it's happening silently...

**Comment by snipe** [comment]
I'd still really like to figure out a better solution here. I guess we could create helpers that lock it down to specific manufacturers, but that's a lot of annoying work just for this. :(

**Comment by marcusmoore** [comment]
> Right - there has to be a better way tho. One new manufacturer per component in the seeders is crap seed data.

I think doing something like this in the seeders
```
$manufacturers = Manufacturers::all();

Component::factory()->ramCrucial4()->create([
    'company_id' => $companyIds->random(),
    'location_id' => $locationIds->random(),
    'manufacturer_id' => $manufacturers->random()->id,
]);
```

By providing `manufacturer_id` the factory doesn't create a new model (if I'm remembering right).

**Comment by snipe** [comment]
I tried that beforehand and it didn't work, but I might have missed something. I might be able to to just inject the manufacturer IDs manually in each of the different types of components, since we already have those set up anyway.

**Comment by marcusmoore** [comment]
We do something similar in the [AssetSeeder](https://github.com/snipe/snipe-it/blob/ab0c009c0db3cabfed8401b3754aa2addfbc111c/database/seeders/AssetSeeder.php#L15) so we can use that for reference.

**Comment by marcusmoore** [comment]
Specifically [getting IDs](https://github.com/snipe/snipe-it/blob/ab0c009c0db3cabfed8401b3754aa2addfbc111c/database/seeders/AssetSeeder.php#L29) and [then using a random one](https://github.com/snipe/snipe-it/blob/ab0c009c0db3cabfed8401b3754aa2addfbc111c/database/seeders/AssetSeeder.php#L83).

**Comment by snipe** [comment]
Not quite the same though, since there is an actual correlation between the manufacturer and the seeded data (Crucial, etc),  so just pulling a random ID wouldn't make sense for the demos.

**Comment by marcusmoore** [comment]
Ah fair point. This might be a use-case for `recycle`

https://laravel.com/docs/10.x/eloquent-factories#recycling-an-existing-model-for-relationships

<blockquote><div><strong><a href="https://laravel.com/">Laravel - The PHP Framework For Web Artisans</a></strong></div><div>Laravel is a PHP web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.</div></blockquote>

**Comment by snipe** [comment]
I think [this](https://github.com/snipe/snipe-it/commit/e0ec6795b57406e100fc80af4b5799eb6b00b757) should handle it for now. Tests pass and db is seeding as expected. We can revisit longer term strategy later.

**Pull request merged**
