### PR TITLE
Add LDAP-Sync for Companies

### PR DESCRIPTION
**Pull request by aj-bi**
# Description

Adds the LDAP sync for the companies. Code is copied from Locations. For people, the company can now also be synchronized.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Did a LDAP-Sync against a Active-Direcotry

**Test Configuration**:
* PHP version: v7.4.28
* MySQL version: 10.5.15
* Webserver version: 2.4.53
* OS version: Linux Debian

# Checklist:

- [x ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aj-bi** [comment]
https://github.com/snipe/snipe-it/issues/10698

**Comment by snipe** [comment]
@uberbrady can you put a review on this? It's been open a while and I think you are the most intimately familiar (recently) with LDAP

**Comment by Peenpower** [comment]
Can anybody tell me the status? or the planning on the road map?

**Comment by SebastianKlimczok** [comment]
+1
I'm very interested in this feature, as this would automate the process of setting the company for every new user, with multicompany enabled.

**Comment by aj-bi** [comment]
@Peenpower , @SebastianKlimczok Feel free to patch your installation yourself. The "code" is almost the same as in "Locations", simply adapted to "Companies". Unfortunately I have no influence... whether it gets into the official repo or not.

**Comment by gertz22** [comment]
+1

**Comment by snipe** [comment]
Hi there - we have a more recent version of this in #10698 and there are a lot of merge conflicts, so I'm going to close this one for now.

**Pull request closed without merging**
