### PR TITLE
Fixed the order expiring assets are listed in notifications

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

image

Fixes # SC-19333

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
@uberbrady is it possible we can use something other than RAW here? Also is this the order we think a user would expect?

**Comment by uberbrady** [comment]
> @uberbrady is it possible we can use something other than RAW here? Also is this the order we think a user would expect?

I don't know that there is another way to do this other than `DB::raw()` (well, `orderByRaw()` is probably doing most of the heavy lifting here) - the problem is that different assets might have different warranty expiration periods, and typically, the order that you'd want to see is what's expiring _first_. It's possible that `orderByRaw()` means that the `DB::raw()` is extraneous - @Godmartinz , can you check that out for us? It's a small thing, it would just mean we're simplifying the code a teensy bit.

But regardless of that small point, it looks like it handles that use case, and it does so in the only way that I can figure out that makes any sense.

So, I think this is the order users would expect, and I think that `orderByRaw()` is the only way you can go about it. I hate raw DB queries as much as the next person, but it definitively solves a problem here.

If there *is* another way to do this without dropping to Raw queries, I certainly don't know what it is :/

**Comment by Godmartinz** [comment]
On it 👍

**Comment by Godmartinz** [comment]
`/DB:raw()` has been removed now 👍

**Pull request merged**
