### PR TITLE
Added Brother 18mm label type

### PR DESCRIPTION
**Pull request by snipe**
I don't know if the sizing is correct on this. Does anyone have an 18mm Brother label printer to test this PR?

### CODE REVIEW

**Comment by michaelortnerit** [comment]
Hello @snipe,

maybe i can test it. I have a P-touch P900W which supports 3.5mm to 36mm i will have a look if we have 18mm. Maybe next week i can give you feedback.

**Comment by snipe** [comment]
Thanks so much, @michaelortnerit!

**Comment by michaelortnerit** [comment]
No problem. I have found a 18mm label. Already cloning the branch and building a docker image for testing. :)

**Comment by snipe** [comment]
Any luck testing this?

**Comment by snipe** [comment]
@michaelortnerit - have you had a chance to test this by any chance?

**Pull request merged**
