### PR TITLE
Allow Sorting Based On EOL Date

### LINKED ISSUE #12372: EOL not sortable
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

EOL column in Assets preview is not sortable in any way.
Tried every date format
demo.snipeitapp.com has the same issue

### Reproduction steps

1. Assets
2. EOL column
3.
...

### Expected behavior

sort by date like purchase cost column

### Screenshots

Screenshot_2022-12-14_at_12 59 39

### Snipe-IT Version

 v6.0.14

### Operating System

Ubuntu 

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by corydlamb**
Allowing sorting via EOL.

# Description

Saw a post ( https://github.com/snipe/snipe-it/issues/12372 ) requesting this, gave this change a test on our server and it seems to work fairly well. If an asset has a buy date and EOL on the model it can sort by the dates.

Fixes #12372

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on my server, another really small change in the asset presenter file.

- [x] Test A
- [ ] Test B

**Test Configuration**:
* PHP version: 8.1.11
* MySQL version 15.1
* Webserver version Apache 2.4.38
* OS version Turnkey Linux (updated to latest version of SNIPE (6.0.14)

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
EOL on the asset isn't sortable because it's not a native database field, it's calculated. 

https://github.com/snipe/snipe-it/blob/2564da648b28845a805629885820717f2f7521d3/app/Http/Transformers/AssetsTransformer.php#L41

https://github.com/snipe/snipe-it/blob/2564da648b28845a805629885820717f2f7521d3/app/Presenters/AssetPresenter.php#L415-L423

**Comment by corydlamb** [comment]
> EOL on the asset isn't sortable because it's not a native database field, it's calculated.
> 
> https://github.com/snipe/snipe-it/blob/2564da648b28845a805629885820717f2f7521d3/app/Http/Transformers/AssetsTransformer.php#L41
> 
> https://github.com/snipe/snipe-it/blob/2564da648b28845a805629885820717f2f7521d3/app/Presenters/AssetPresenter.php#L415-L423

Oh I see, my apologies!

**Comment by snipe** [comment]
I think we'd need to do something more like this to make it work: #12393

**Comment by snipe** [comment]
I'd be happy to go into more detail on that PR if you have questions - it does get a bit in the weeds. Definitely appreciate you trying to solve it via this PR though. As you can see, it's a little trickier than it first seems offhand, as so many things are.

**Comment by corydlamb** [comment]
> I'd be happy to go into more detail on that PR if you have questions - it does get a bit in the weeds. Definitely appreciate you trying to solve it via this PR though. As you can see, it's a little trickier than it first seems offhand, as so many things are.

Thank you so much! I really appreciate how welcoming and freindly to novices like myself y'all are! I guess I'm just curious as to why calculated values shouldn't be sorted. There's a lot of reading up I should probably do on php tbh 😅

**Comment by snipe** [comment]
It's honestly largely just the complexity of the query in the database (AND people have asked to be able to edit that date directly in the past, so we can kill two birds with one stone here.) Even though we *technically* only officially support MySQL and MariaDB, I do know that some folks are using other databases (pgSQL, SQLite, etc) so we generally try to keep those queries as simple as possible for maximum compatibility. That said, my PR could get rejected by my team come Monday, so... we'll see :D 

So it's a bit more of a product decision than it is a technical one, and there's no way you could have known every little thing that folks have asked for here.

**Pull request closed without merging**
