### PR TITLE
Added #9413: AssetModel files endpoints to API

### PR DESCRIPTION
**Pull request by r-xyz**
# Description

#14698 added files API endpoints for assets. Files can also be uploaded to models, and will show up under additional files.
This PR adds similar endpoints to models.

Added #9413 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Upload a file:
```curl --request POST --url http://localhost:8080/api/v1/models/1/files --header "Authorization: Bearer xxxxxxxxxx" -F "file[]=@test.txt" --verbose```
- [x] List files:
```curl --request GET --url http://localhost:8080/api/v1/models/1/files --header "Authorization: Bearer xxxxxxxxxx" --header 'accept: application/json' --verbose```
- [x] Get a file:
```curl --request GET --url http://localhost:8080/api/v1/models/1/file/1 --header "Authorization: Bearer xxxxxxxxxx" --output downloadedfile --verbose```
- [x] Delete a file:
```curl --request DELETE --url http://localhost:8080/api/v1/models/1/file/1 --header "Authorization: Bearer xxxxxxxxxx" --header 'accept: application/json' --verbose```
Tested with PDF

**Test Configuration**:
* PHP version: 8.2
* MySQL version docker
* Webserver version: docker
* OS version: docker alpine

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by r-xyz** [comment]
**NOTE:** I made a php test based on #14698 , but I was not able to run it in the generated image due to unrelated bug.
Running collision 7.x requires PHP 11.x

```bash
php artisan test
[2024-08-21 17:46:48] production.ERROR: Error: Class "PHPUnit\Runner\Version" not found in /var/www/html/vendor/nunomaduro/collision/src/Adapters/Laravel/Commands/TestCommand.php:74
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): NunoMaduro\Collision\Adapters\Laravel\Commands\TestCommand->handle()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#6 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run()
#8 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#9 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#12 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#13 {main}  
[2024-08-21 17:46:48] production.ERROR: Class "PHPUnit\Runner\Version" not found {"exception":"[object] (Error(code: 0): Class \"PHPUnit\\Runner\\Version\" not found at /var/www/html/vendor/nunomaduro/collision/src/Adapters/Laravel/Commands/TestCommand.php:74)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): NunoMaduro\\Collision\\Adapters\\Laravel\\Commands\\TestCommand->handle()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#6 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#8 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#9 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#10 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#12 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#13 {main}
"} 

   Error 

  Class "PHPUnit\Runner\Version" not found

  at vendor/nunomaduro/collision/src/Adapters/Laravel/Commands/TestCommand.php:74
     70▕      * @return mixed
     71▕      */
     72▕     public function handle()
     73▕     {
  ➜  74▕         $phpunitVersion = Version::id();
     75▕ 
     76▕         if ($phpunitVersion[0].$phpunitVersion[1] !== '10') {
     77▕             throw new RequirementsException('Running Collision 7.x artisan test command requires at least PHPUnit 10.x.');
     78▕         }

      +12 vendor frames 

  13  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by snipe** [comment]
PHP 11? That can’t be right. PHP 8.3 just came out

**Comment by r-xyz** [comment]
> PHP 11? That can’t be right. PHP 8.3 just came out

Sorry, PHP Unit 10.x. But tests seem to run on CI, so maybe something is wrong with my dev setup. I am using `dev.docker-compose.yaml` setup.

**Comment by r-xyz** [comment]
Fixed some minor bugs I missed in the first commit.
I re-tested manually the functionality, and it works. All tests are now passing on CI, but I am still unable to run them on the locally built docker image.

**Pull request merged**
