### PR TITLE
Update Docker: Add PostgreSQL support for the Dockerfile

### PR DESCRIPTION
**Pull request by gianklug**
# Description

* Added the ability to set the type of the database to use via another env variable
* Renamed all the `MYSQL_` env variables to `DB_` to make them more generic
* Added the PHP/PDO modules for `pgsql`

See #1920 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

I could not yet do any tests if the PostgreSQL connection works, I will add more information later.

**Test Configuration**:
* Docker 

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Thanks for this - I think this is the wrong approach though. We can add things, and as I’ve stated very clearly - we do not officially support Postgres and likely will not anytime soon - but you’d be better served adding a Postgres driver, versus trying to change existing var names

**Comment by gianklug** [comment]
We could just leave it at adding the PostgreSQL (PDO) packages for this PR. However it is still a bit misleading to have variables called `MYSQL_*` if connecting to PostgreSQL would be possible after this PR.

**Comment by gianklug** [comment]
Best solution would be to stick 1:1 to the Laravel database variable names.

AFAIK there isn't a way to provide "aliases" for Docker env variables so we could provide backwards compatibility for the current variable names. Thus, this would be a breaking change...

**Comment by gianklug** [comment]
@snipe could you please comment on my suggestions again?

**Comment by snipe** [comment]
There isn't really a thing as "laravel database variable names" - those are turned into application variables via `config/database.php` - but as time goes on, there may be additional things that pgSQL needs that MySQL doesn't, so that space could potentially become convoluted.

**Comment by gianklug** [comment]
@snipe I'm talking about the default laravel `.env` keys (see [here](https://github.com/laravel/laravel/blob/9.x/.env.example)).
Even though postgres might need additional things in the future, however as of right now the addition of the postgresql packages would make it possible to use postgres when containerized and not only on a standalone installation.

**Review by uberbrady — CHANGES_REQUESTED** [review]
Thanks for adding this; I'm sure plenty of users are using Postgres and would appreciate this.

However this is going to be too much of a breaking change for those users who do already have a working Docker configuration - we can't make breaking changes like this without plenty of warning.

I've been thinking for the past few months that our current method of requiring `--link` parameters and such is not the right way to go, and we need to try our best to try and fix that. It's hard to do without breaking current users, but I do have some ideas.

But in the meantime, if you just need to populate those values, you can re-use the (terrible) variable names like `MYSQL_PORT_3306_TCP_ADDR` etc. The one place that you add here that I would like for us to be able to support this in Docker is the `DB_CONNECTION` - if you can give me a more focused PR that allows people to reset that to `pgsql`, but can manage to leave a 'sane default' of `mysql` for those who don't set `DB_TYPE`, I would definitely be willing to take that. And, as I mentioned, I'm pondering some clever code-level switches that will dynamically read the appropriate variables (when invoked in a 'docker' context) - but that's not going to be coming out for a while yet.

**Comment by gianklug** [comment]
@uberbrady sadly it's not just the `DB_CONNECTION` var that is needed but also the PDO-pgsql module as you can see in my changes.

I will however try to revert the name changes of the variable names when I find time.

Meanwhile we've come up with a meta-container which is just for postgres usage:
https://github.com/adfinis/container-image-snipeit-pg/pkgs/container/container-image-snipeit-pg

<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 83 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div></blockquote>

**Pull request closed without merging**
