### PR TITLE
Hopefully fixes #8418 - migrations on new install go wonky because of…

### LINKED ISSUE #8418: Logic error with setting up V5 beta 3
- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
During the migration data from version 4 to version 5, I was having trouble with the installer adding the `ad_append_domain` field in settings every time. I narrowed the problem to `database\migrations\2020_02_04_172100_add_ad_append_domain_settings.php` Line 17-19. When in the initial steps of setting up the installer will attempt to keep adding the field to the settings table. I can give more screenshots to make sure this gets patched. This had me scratching my head for the last 3 days. I was able to fix the issue by commenting out the lines in question. This seemed to have solved the issue. I think a simple conditional statement should be fine. As I have not learned PHP yet, I figure I would report it.

**To Reproduce**
1. Make a fresh install of V5 Beta 3
2. Run the migration command
3. Run through setup
4. Visit instance.
5. See error

**Expected behavior**
The installer completes setup with data intact

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.0-beta-3 build 4190 (gec723a3da)
 - OS: Windows
 - Web Server: Apache
 - PHP Version 7.4.8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 85.0.4183.83

**Error Messages**
https://gist.github.com/tannersouva/3e3c7a168670d952539f9551aa14fe3b

### PR DESCRIPTION
**Pull request by snipe**
FYI, @uberbrady -- <del>as it is right now, when I try to seed, I get:</del>

```
✨snipe@deepthought✨ snipe-it  (integrations/rc5-4-2020-08-31-dev-into-master) $ php artisan db:seed

In Setting.php line 347:

  Call to a member function getAttributes() on null

```

EDIT: Nevermind, I am a dumbass.

### CODE REVIEW

**Review by uberbrady — APPROVED** [review]
Yes, LDAP sync still works with this and so does LDAP login, at least on my JumpCloud account. And, more importantly, when I mess up the password it very much does _not_ let me log in, which is what we want.

I'm still seeing some php7.4 problems here - mostly dealing with `ldap_control_paged_result` (thanks a *lot*, php7.4!) so I'm going to keep trying to figure out how to suppress those deprecation warnings, but that's a totally separate issue.

**Comment by snipe** [comment]
@uberbrady ty for the extra set of eyes!

**Comment by Skywalker-11** [comment]
@uberbrady adldap2 contains fixes with release v10.3.0 that should solve the `ldap_control_paged_result` errors
https://github.com/Adldap2/Adldap2-Laravel/issues/838

**Comment by snipe** [comment]
@Skywalker-11 TY - IIRC, that version is a bit of a departure from the original package though. Right now we're trying to prep for v5, and once that's out, we'll be reworking LDAP (again. sigh) to pull it into their newer package. We just cannot manage any more delays on this version It's already been too long.

**Comment by Skywalker-11** [comment]
Just to prevent confusion. The actual fix for the error is in the original adldap2/adldap2 package https://github.com/Adldap2/Adldap2/releases/tag/v10.3.0 and should probably be backwards compatible



<blockquote><div> GitHub</div><div><strong><a href="/Adldap2/Adldap2/releases/tag/v10.3.0">Release v10.3.0 · Adldap2/Adldap2</a></strong></div><div>Fixed

ldap_control_paged_result deprecation back-port from LdapRecord

#760, #762
dce42d4, 0f0227c, 42df018
Thanks to @kkatpcc!



Changed

Provider connections are now no longer closed manually t...</div></blockquote>

**Comment by HinchK** [comment]
In May, I found LdapRecord solved the underlying business problem, was relatively easy to implement without reliance on `Schema` & leveraged the ORM properly.   The author has done an awesome job of documenting his decision making.   
 
https://github.com/snipe/snipe-it/issues/7896

https://stevebauman.ca/posts/why-ldap-record/

Whichever way you choose, I'm sure it will be great.  May the road rise up to meet you, and the ldap-syncing be at your back.

<blockquote><div><strong><a href="https://stevebauman.ca/posts/why-ldap-record">Why LdapRecord?</a></strong></div><div>Why LdapRecord was created instead of supporting Adldap2</div></blockquote>

**Pull request merged**
