### PR TITLE
Set custom field's default value when creating a new asset using the API

### PR DESCRIPTION
**Pull request by JuustoMestari**
This will fix issue #6720 by using the custom field's default value if no other value is provided.

### CODE REVIEW

**Comment by snipe** [comment]
How do we handle this if the actual desired value for the custom field is null though?

**Comment by JuustoMestari** [comment]
That is a good question. It would be a case where the user sets a default value for a field but still want to save a null value.
Would it help to use another value other than null in the check? Any ideas?

**Comment by AllenRDCo** [comment]
> How do we handle this if the actual desired value for the custom field is null though?

Isn't that the point of a default value? If nothing is entered it is supposed to use the default? If you really want to override the default and set it to null then the user should be able to just clear out the field and it will set to null. The code should merely be pre-populating the field with the default value so that when the form is saved that entry is saved as well. It should not be setting it to the default behind the scenes after the user has submitted the form if the value being submitted is null. 

I just setup a new installation of snipe-it and was trying to use the fieldset in an asset model to set the Mfg. EOL date to a default value for the particular asset model any time a new asset is created with it, but instead it's leaving everything null so I don't see the point of even having the ability to set a default it it's not actually being used. I still have to manually set the field when creating a new asset under the asset model which defeats the whole point of having a default value. This is all through the web interface mind you, not the API like the original issue was submitted for.

**Comment by Oscillometer** [comment]
This is still an issue, as default values are not applying to new/existing assets with null fields.

**Comment by snipe** [comment]
Hi @JuustoMestari - thanks again for submitting this. The code base had (obviously) changed quite a bit since you opened this PR - that's my fault, and I'm sorry about that. v5 meant there were SO many changes between master and develop and it made it a real challenge to do PR reviews in a timely way. 

There were merge conflicts here so I'm going  to close this PR, but I did add you as a contributor anyway, as I just built on the changes you originally made. Thanks again, and I'm sorry we dropped the ball on this PR. 

This issue has been fixed and merged into the `develop` branch, and will be in the next release.

trek-nods

**Pull request closed without merging**
