### PR TITLE
Added supplier to components and consumables

### LINKED ISSUE #7795: Allow components to be mapped to a supplier
**Server:**
 - Snipe-IT Version: v4.8.0 - build 4186 (master)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.2.24-0ubuntu0.18.04.2

**Is your feature request related to a problem? Please describe.**
I have lots of components which require warranty / service and the service is provided by the original supplier who supplied the product. 

**Describe the solution you'd like**
It would be great if I can see all the components supplied by a specific supplier in the supplier view page along with a warranty plan.

**Describe alternatives you've considered**
Adding components as assets but that seems overkill and there is no use of components in that case. Most components make up an asset.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by snipe**
This fixes #7795. Adds supplier ID to the consumables and components tables, and displays components and consumables in the suppliers view.

### CODE REVIEW

**Comment by rkthamizhan** [comment]
Suppliers not shown
oz5powgi

After added Supplier 500 Server error

**Comment by rkthamizhan** [comment]
after appended above all coding, in Component tab i can see the supplier but not in 
Consumables. and all exisiting supllier information got disappered 
And try to edit Component tab and add supplllier information it shows "500  server error" after click the save button

**Comment by snipe** [comment]
> after appended above all coding

Never do this. Just wait for the PR to be merged so you can be sure it's thoroughly tested. My guess is that you didn't run migrations.

**Comment by rkthamizhan** [comment]
> > after appended above all coding
> 
> Never do this. Just wait for the PR to be merged so you can be sure it's thoroughly tested. My guess is that you didn't run migrations.

yes im not run the migration, pls assist me with the executable command..thanks

**Comment by rkthamizhan** [comment]
hi i revoked all the changes (restored from snapshot)..
now i can't import csv files shows error "500 server error" on the latest version -Version v6.1.0 - build 10161 (master)

**Pull request merged**
