### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by koiakoia**
corrected grammatical error

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, providing screenshots where practical. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by koiakoia** [comment]
Thanks for the tip I realized I had the wrong branch but glad you saw first saved some time.  Total newb here but want to help where I can.  Appreciate your thoughtful feedback and direction.

**Comment by snipe** [comment]
Heh, I think there were a lot of changes since you pulled that branch - notice there are a bunch of additional changes in that PR that you didn't make? You might try rebasing here. (Or if it's easier, I can just apply that change myself and add you to the contributors list.)

**Comment by koiakoia** [comment]
Don't want to mess it up for you or create extra work. Appreciate your willingness to work with me on this.  Feel free to add yourself and add me to contributors.  Great work thanks for your help.

**Comment by snipe** [comment]
I've applied the patch directly - ty!

**Pull request closed without merging**
