### PR TITLE
Fix #4275: advanced search using custom fields

### LINKED ISSUE #4275: Advanced Search Returns No Results
#### Expected Behavior (or desired behavior if a feature request)
Expecting results when using advanced search on assets page.
-----

#### Actual Behavior
No results returned when using most searches, or in some cases search is not filtering properly.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.0.13 build 273 (gab3f5f4)
- Version of PHP you're running 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running 10.1.28-MariaDB
- What OS and web server you're running Snipe-IT on Ubuntu 16.04.3/apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /hardware
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[2017-10-20 13:49:29] production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'model' in 'where clause' in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77

- Include what you've done so far in the installation, and if you got any error messages along the way. Installed fresh and imported database from same version.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/50573328-advanced-search-returns-no-results?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anarute**
# Description

When filtering assets using custom fields, the bootstrap table toolbar tries to match its header columns with the properties
in the root of the item object.

Since the custom fields are an array inside the property `custom_items` of the item instead of flatten properties, the check
done by bootstrap table will always be false, resulting in the exclusion of all items searched using a custom field.

I know it's not a good practice to change third party libraries but this was the simplest fix I could think without doing major refactoring, also it seems that newer versions of bootstrap table toolbar should fix this, allowing us to get rid of this patch when migrating to a newer version of it.
I don't know if the plan is to upgrade bootstrap table toolbar in 5.0, but since doing so will require a lot of work I believe this could be a temporary fix for 4.x until the upgrade is complete.

Please note that this PR is against `master` instead of `develop` because I wasn't able to run the application with the `develop` branch locally.

Fixes #4275

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I have tested locally serving the application with `php artisan serve`.
See the gif below of the search in action:

snipe-advancedsearch

**Test Configuration**:
* PHP version:  7.4.9
* MySQL version: mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64)
* Webserver version: I was running locally with `php artisan serve` -  so not really sure about that, Laravel Framework 5.5.49?
* OS version: Ubuntu 18.04.4 

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
This is an amazing PR, thank you so much. I still need to test this a bit more, but if it works as advertised, I cannot thank you enough. It's been on my list of stuff to fix for literally years. <3

**Comment by snipe** [comment]
So, you're also right here - it's not good practice to change third party libraries. Mostly because v5 pulls right from the npm modules, so it will get overwritten. This is great work, and I'd love to include it, but maybe we can add this into the snipeit.js instead, extending out the bootstrap-tables library, so it can be sustainable moving forward?

**Comment by anarute** [comment]
> So, you're also right here - it's not good practice to change third party libraries. Mostly because v5 pulls right from the npm modules, so it will get overwritten. This is great work, and I'd love to include it, but maybe we can add this into the snipeit.js instead, extending out the bootstrap-tables library, so it can be sustainable moving forward?

@snipe after some effort me and @kov managed to overwrite the library `initSearch` method :)
it made sense to do this in the `bootstrap-table.blade.php` file as it's where the bootstrap table is called, but let me know if you prefer it in `snipeit.js` instead.

I added some comments to point exactly what was changed from the original, in case newer versions of the lib fixes this issue and this change can be reverted.

**Comment by 119155012** [comment]
@anarute Thanks for the fix, that's a big help.
And there's a similar issue in Audit Log page, the search bar seems narrow in **`Notes`** scope.
Not worked at global scope, e.g., **`Audit`**, **`Admin`**, **`Item`**, **`Location`**.

I think it's still a bootstrap-table-toolbar.js issue. @snipe

**Comment by anarute** [comment]
Hello there, any estimation of when this could be merged? at least for 4.x versions?

**Comment by snipe** [comment]
We will not be maintaining v4 other than urgent security issues.

**Comment by snipe** [comment]
I’ll see if we can make this work on v5 tho

**Comment by snipe** [comment]
We're currently running the latest bootstrap-tables on v5

**Comment by uberbrady** [comment]
I actually think we can close this out, since the advanced search **does** work as shown here in v5 (probably due to the Bootstrap Tables upgrade that @snipe referred to). Regardless, thanks for the contribution @anarute and we'd love to see what you think of next!

**Pull request closed without merging**
