### PR TITLE
Remove unnecessary executable permission from static files

### PR DESCRIPTION
**Pull request by PeterDaveHello**
# Description

Remove unnecessary executable permission from static files, those files aren't and shouldn't be executable.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
@PeterDaveHello - I don't think I'm comfortable merging a PR with over 600 changed files. It would be too easy for us to miss something that could actually cause issues - plus this PR doesn't really solve any issues, since all of the files seem to be .js, .css or .git* files, so there's no security issue involved. :(

**Comment by PeterDaveHello** [comment]
I know it's scary to involve too many files in the same time, just their executable permission doesn't make sense either 😅

**Comment by snipe** [comment]
It’s not scary exactly - just policy. Plus different user+group combos require different things, so a blanket change like this can lead to dragons.

**Comment by PeterDaveHello** [comment]
Well, it doesn't really seem to be a policy here? Those files just aren't executable, are they 😄 I'll respect the decision here, but just a little bit curious.

**Pull request closed without merging**
