### PR TITLE
Added warranty confirmation to asset maintenance table

### LINKED ISSUE #13152: Warranty is not showing in Asset Maintenances
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Warranty is not showing in Asset Maintenances after creating maintenance for asset with option for Warranty Improvement is check true.

### Reproduction steps

1. Create asset
2. Go to asset detail>maintenance
3. Create maintenance, check the Warranty to true
4. Go to assets>asset maintenance
5. The warranty is empty, no true/false

### Expected behavior

1. Create asset
2. Go to asset detail>maintenance
3. Create maintenance, check the Warranty to true
4. Go to assets>asset maintenance
5. The warranty is not empty, there is true/false

### Screenshots

_No response_

### Snipe-IT Version

v6.1.1-pre build 10653 (g11cd875c6)

### Operating System

Windows

### Web Server

Apache

### PHP Version

7.4.33

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
Adds a response if an asset under maintenance is covered/improved by a warranty in the table view of maintenance requests.

image

Fixes #13152 

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by snipe — APPROVED** [review]
Can we use the `trueFalseFormatter` here instead to make it more consistent with our other views?

**Review by snipe — CHANGES_REQUESTED** [review]
Sorry, I meant to request changes here not approve. :(

**Comment by Godmartinz** [comment]
@snipe Done 🙂

**Comment by snipe** [comment]
We'll probably also want to add that `is_warranty` field to the API controller in the allowed columns so it can be sorted on

**Pull request merged**
