### PR TITLE
Use `htmlentities()` instead of `htmlspecialcharacters()` on Custom Field Listbox Values

### PR DESCRIPTION
**Pull request by spencerrlongg**
# Description
On the tin, this seems to allow the list box to function as expected, fixing an issue reported by a user. If there's anything you'd like me to test specifically I'm more than happy to do so, but from what I can tell this should resolve the issue. 

https://www.php.net/manual/en/function.htmlentities.php

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Checked to make sure values in listboxes are still coming through and matching correctly to their DB values. 

**Test Configuration**:
* PHP version: 8.1
* MySQL version: 8.2

### CODE REVIEW

**Comment by snipe** [comment]
I'd love to see some tests here, and also some proofs that it's been tested for [XSS vulns](https://snipe-it.readme.io/docs/contributing-security). The reason we were using the old method is that we need `13"` to actually be `13"` in the database, not `13&quot;`, since that won't match up. I feel like we might need to do something on the backend, like: 

1) encode that in HTML on the front end to prevent XSS and also to not break HTML
2) decode it before storing on the backend

**Comment by snipe** [comment]
Also looks like we have 8.1.1 failing test?

**Comment by spencerrlongg** [comment]
> Also looks like we have 8.1.1 failing test?

Looks like flakey test, re-ran and it passed. 



> I'd love to see some tests here, and also some proofs that it's been tested for [XSS vulns](https://snipe-it.readme.io/docs/contributing-security). The reason we were using the old method is that we need `13"` to actually be `13"` in the database, not `13&quot;`, since that won't match up. I feel like we might need to do something on the backend, like:
> 
> 1. encode that in HTML on the front end to prevent XSS and also to not break HTML
> 2. decode it before storing on the backend

Looking into this.

**Comment by spencerrlongg** [comment]
@snipe So, turns out that the actual problem here is that on the initial `store` of a custom field the value isn't escaped - but it _is_ once it's `update`d, and then the output escaping starts working. So, pivoting this PR to just escape the initial saved value. 

Probably need to do some more testing on this and come up with a way to fix existing data, but that's the update for right now.

**Comment by spencerrlongg** [comment]
Alright, so, fixed the problem with the escaping on update, so we now save unescaped raw input on both store and update. 

Then realized that blade's echo helper already does the escaping for us, so `htmlspecialcharacters()` is redundant (and causes some weird behavior), so that's removed now. 

Attaching a couple screenshots of XSS testing. 
image
image
image

**Comment by spencerrlongg** [comment]
@snipe friendly poke

**Comment by spencerrlongg** [comment]
@snipe friendly poke

**Pull request merged**
