### PR TITLE
fix slack channel notifications

### PR DESCRIPTION
**Pull request by stefanstidlffg**
# Description

As the slack notification doesnt use the channel which can be configured in the admin settings, this PR should fix that.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I didnt test it as I dont have an environment at hand.

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marcusmoore — APPROVED** [review]

**Comment by marcusmoore** [comment]
Good catch. Thanks @stefanstidlffg 😄

**Comment by snipe** [comment]
I approved this, since Marcus is a smart cookie, but I'm kind of unclear on what problem this solves. We have an internal test channel which does work, so not sure what change/broke/etc, since using the custom channel has always worked in our tests. (I man also very jet-lagged and cannot brain properly yet, so I might be missing something that we bonked a while back.)

**Comment by stefanstidlffg** [comment]
Thank you for merging!
I think the problem I fixed is, that if you use the slack token for multiple applications and the default channel you created the token for is different to the configuration in snipeit, it now uses the configured channel and not the default one.




Am 08.06.2023 06:53 schrieb snipe ***@***.***>:
I approved this, since Marcus is a smart cookie, but I'm kind of unclear on what problem this solves. We have an internal test channel which does work, so not sure what change/broke/etc, since using the custom channel has always worked in our tests. (I man also very jet-lagged and cannot brain properly yet, so I might be missing something that we bonked a while back.)

-- 
Reply to this email directly or view it on GitHub:
https://github.com/snipe/snipe-it/pull/13123#issuecomment-1581887747
You are receiving this because you were mentioned.

Message ID: ***@***.***>
[EXTERNE EMAIL] Bitte klicken Sie NICHT auf Links oder Anlagen, es sei denn, Sie kennen die Absenderadresse und wissen, dass der Inhalt sicher ist.
******************************************************************************************************************************
Innovationen verbinden. Vernetzen Sie sich mit uns auch auf Linkedin!
FFG Disclaimer / Legal notice: http://www.ffg.at/Disclaimer
******************************************************************************************************************************

**Comment by marcusmoore** [comment]
> I think the problem I fixed is, that if you use the slack token for multiple applications and the default channel you created the token for is different to the configuration in snipeit, it now uses the configured channel and not the default one.


@snipe yup...that's exactly what was happening. Thanks again @stefanstidlffg

**Pull request merged**
