### PR TITLE
Fixed #14483 - Added deeplinking to search/sort/pagination

### LINKED ISSUE #14483: [Feature Request]: Trigger searches from the URL
### Is your feature request related to a problem? Please describe.

It would be handy to be able to share searches.

### Describe the solution you'd like

Allow the search term to be appended to the URL - For example;

snipe-it.io/hardware/audit/due?search="room%201" could return all assets in Room 1 that are due for an audit.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snipe**
This adds deep linking functionality to search/sort/pages so you can link directly to results in the table results.

### CODE REVIEW

**Comment by snipe** [comment]
Hm, just found a bug here that's limiting the number of pages to a lower threshold than we specify in the BS table code. Looking into this now.

**Comment by snipe** [comment]
Never mind - I'm a dumbass. It works fine lol

**Comment by ShaunNeighbourSwale** [comment]
Thanks - Should I give it a couple of days before asking support to upgrade our hosted instance?

**Comment by snipe** [comment]
Nope, you can open a ticket at support@snipeitapp.com and we can get you updated right away

**Comment by snipe** [comment]
(Make sure to tell us your hosted subdomain in that ticket tho 😜)

**Comment by ShaunNeighbourSwale** [comment]
Thank you!

**Pull request merged**
