### PR TITLE
Update feature_request.yml

### PR DESCRIPTION
**Pull request by benwa**
Correcting the label/description fields

# Description

The description field in the Feature Request is missing

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Thanks!!

**Comment by benwa** [comment]
Welp I'm not sure what goof'd up but it removed the Feature Request option under Issues. The formatting looks all correct to me...

**Comment by snipe** [comment]
Hm... I just updated it to be a little shorter, took out some quote marks, etc and it seems to have brought it back.

https://github.com/snipe/snipe-it/issues/new?assignees=snipe&labels=feature+request&template=feature_request.yml&title=%5BFeature+Request%5D%3A+

(We mostly don't care what operating system, etc, for feature requests, since a feature should work across all OSes)

**Comment by snipe** [comment]
I blame YAML.

```json
{
"joke" : "I was going to write the joke in YAML but after so many parsing errors I realized it would be easier in JSON"
}
```

https://twitter.com/paceaux/status/1335002446918262784?s=21&t=sAi16-VE5fOfccSU3cZrlw

**Pull request merged**
