### PR TITLE
Fixed an issue with links colors on black dark skin

### PR DESCRIPTION
**Pull request by Godmartinz**
main text was set to black, I reset it to white and changed the a:visited to text-sub
Screen Shot 2021-02-01 at 10 04 22 AM

### CODE REVIEW

**Comment by snipe** [comment]
Looks great - did you check the other dark skins as well so that (if needed) we can fix it everywhere?

**Comment by snipe** [comment]
Also on your commits/PRs moving forward, if we have an issue in CH, can you try to remember to reference the CH issue number. 

There is a little helper thingie that generates the commit text that ties it back to the GH commit. 

Screen Shot 2021-02-01 at 12 54 07 PM

Screen Shot 2021-02-01 at 12 54 14 PM

Otherwise we have to do it manually. Thanks!

**Comment by Godmartinz** [comment]
The other dark skins look great, but I did just come across 1 more issue in the black dark skin. Don't merge just yet.

**Comment by snipe** [comment]
@Godmartinz Roger that! I await your go-ahead :)

**Comment by Godmartinz** [comment]
@snipe good to go 🚀

**Comment by snipe** [comment]
Noice! 

BondJumpIntoRippedTrain

**Pull request merged**
