### PR TITLE
Commenting on a scope in Models/Company.php

### PR DESCRIPTION
**Pull request by akemidx**
# Description
This is only a code comment

### CODE REVIEW

**Comment by snipe** [comment]
This is a good start! Can you fix the typo tho? `queires` vs `queries`? 😁

**Comment by snipe** [comment]
Also we typically wouldn't say "Adding" in a static code comment, since we expect (or hope) that the code exists for a while. The comment explains what the code currently does, not the action that was required to get it there. "Scope for queries so only authorized users will be able to see a company's ID value." 


Except I am not even sure that's what that query scope does lol

I think it just determines whether or not the logged in user has a company (and if so, it scopes the other queries to only let them see stuff that belongs to that company)

**Comment by snipe** [comment]
Looks good - is this ready to go or are you still making changes?

**Comment by akemidx** [comment]
this is ready to go

**Pull request merged**
