### PR TITLE
allow location_id to be set seperately from rtd_location id via the w…

### PR DESCRIPTION
**Pull request by bveina**
addresses: #6566 
now if rtd_location_id is provided in the post request the location_id is nolonger overwritten, and the request now updates location_id

i apologize for the branch name, i was having some trouble with git commands.

### CODE REVIEW

**Comment by dmeltzer** [comment]
Hi,

The location ID is determined based on what the item is checked out to.  If it's incorrect, you should be updating the location of the user/whatever it's checked out to.  location_id only exists as a real column because the database was getting angry with all of the table joins/polymorphic adventures.

**Comment by bveina** [comment]
id like to offer a different view on this. a users location is where you can find the user. but not everything checked out to the user will be in that location. in my case our users have offices, so that is the users location.  but their equipment could be anywhere. so it is very important for me to make the distinction between user location and asset location.

**Comment by bveina** [comment]
the basic audit workflow on my api scripting below my demonstrate my point better than my inarticulate ramblings...

```python
r = audit(myItem['asset_tag'],roomId)

if (isDeployedToLocation(myItem) and deployedLocationId(myItem) != roomId): 
    # asset not found in the location its checked out to so
    # checkin asset, with a note to the audited room, then check it out to the new room
    # if needed
    checkIn(myItem,roomId=roomId,note='auto checkin during audit')
    if autoMove:
        checkOut_location(myItem,roomId,note='auto checkout during audit')
elif isDeployedToUser(myItem) and myItem['location']['id']!=roomId:
    #deployed to a user
    if removeUser==True:
        checkIn(myItem,roomId=roomId,note='auto checkin during audit')
    update_location(myItem,roomId)
else:
    #not signed out to a user, or a location so in addition to auditing it, change its location.
    update_location(myItem,roomId)
```

**Comment by dmeltzer** [comment]
I'll allow @snipe to weigh in, but I think that while your usecase is valid, it's not how things are currently designed to work.  The location_id is updated in a lot of places in response to a lot of events based on the assumption that it reflects checkin/checkout.  Setting it directly is going to require workarounds in all of those locations based on my recollection.  I think that this would require extending the user to have multiple locations, or checking the asset out to a location directly.  It's been a while since I've been deep in the code, however.

**Comment by bveina** [comment]
i tracked down where/ when the line in question was added. for a long time only the rtd_location_id could be updated. it looks like at some point in the past some "the great migration" happened. the commit in question where the location = rtd_location was added is cc7be5f947b8c8aa1b49adb5416939a806a91768 . im just getting started with this code base but could this be a copy/paste typo? @snipe, do you remember doing this, and why?

**Comment by laurolima** [comment]
This would be good for my use case, as I have assets that can report their location in real time to snipe-it. Perhaps a new hardware API endpoint be of any help towards fixing this issue?

By the way, this issue seems somewhat related to #6743.

**Comment by snipe** [comment]
Ugh - I’m so sorry, and this sucks to have to write. I assume you have abandoned all hope in having this merged - and rightly so perhaps, because its very old. That’s on us, not you. We made a buttload of changes to the codebase since this was opened, and it’s hard to determine whether this is actually even still workable now. 

I’m going to close this PR, but please know that you have our thanks, and if you’re still using Snipe-IT, we’re going to try to manage our PRs a little better moving forward. The roads to v5 was long and fraught with peril, and we didn’t always do a great job at being there for the folks who were trying to help us.

**Pull request closed without merging**
