### PR TITLE
[Snyk] Upgrade alpinejs from 3.13.10 to 3.14.0

### PR DESCRIPTION
**Pull request by snipe**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br />snyk-top-banner

<h3>Snyk has created this PR to upgrade alpinejs from 3.13.10 to 3.14.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.

<hr/>

- The recommended version is **1 version** ahead of your current version.

- The recommended version was released on **22 days ago**.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>alpinejs</b></summary>
    <ul>
      <li>
        <b>3.14.0</b> - <a href="https://github.com/alpinejs/alpine/releases/tag/v3.14.0">2024-05-21</a></br><h2>Changed</h2>
<ul>
<li>✨ Enhances clicks with key modifiers <a href="https://github.com/alpinejs/alpine/pull/4209" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4209/hovercard">#4209</a></li>
<li>Update transition.md - changed span to div <a href="https://github.com/alpinejs/alpine/pull/4215" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4215/hovercard">#4215</a></li>
<li>collapse: remove overflow hidden even if height does not match perfect <a href="https://github.com/alpinejs/alpine/pull/4203" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4203/hovercard">#4203</a></li>
<li>Fix error: TypeError: i is not a function <a href="https://github.com/alpinejs/alpine/pull/4204" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4204/hovercard">#4204</a></li>
<li>Adjust code block according to example <a href="https://github.com/alpinejs/alpine/pull/4197" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4197/hovercard">#4197</a></li>
<li>Higher visibility in docs about needing x-data for things to work <a href="https://github.com/alpinejs/alpine/pull/4194" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4194/hovercard">#4194</a></li>
</ul>
      </li>
      <li>
        <b>3.13.10</b> - <a href="https://github.com/alpinejs/alpine/releases/tag/v3.13.10">2024-04-24</a></br><h2>Changed</h2>
<ul>
<li>Comma modifier to keyup and keydown events <a href="https://github.com/alpinejs/alpine/pull/4170" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4170/hovercard">#4170</a></li>
<li>Fix morphing root level state <a href="https://github.com/alpinejs/alpine/pull/4169" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4169/hovercard">#4169</a></li>
<li>Fix morph when x-for is used inside x-teleport <a href="https://github.com/alpinejs/alpine/pull/4168" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4168/hovercard">#4168</a></li>
<li>Fix form reset for x-model radio, checkbox arrays, select multiple and various modifiers <a href="https://github.com/alpinejs/alpine/pull/4159" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4159/hovercard">#4159</a></li>
<li>Wrong plugin name in Sort docs <a href="https://github.com/alpinejs/alpine/pull/4165" data-hovercard-type="pull_request" data-hovercard-url="/alpinejs/alpine/pull/4165/hovercard">#4165</a></li>
</ul>
      </li>
    </ul>
    from <a href="https://github.com/alpinejs/alpine/releases">alpinejs GitHub release notes</a>
  </details>
</details>

---

> [!IMPORTANT]
>
> - Check the changes in this PR to ensure they won't cause issues with your project.
> - This PR was automatically created by Snyk using the credentials of a real user.

---

**Note:** _You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs._

**For more information:** 

> - 🧐 [View latest project report](https://app.snyk.io/org/snipe/project/3d53e1dd-b8bf-46b5-ba61-18ce26933166?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)
> - 📜 [Customise PR templates](https://docs.snyk.io/scan-using-snyk/pull-requests/snyk-fix-pull-or-merge-requests/customize-pr-templates)
> - 🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/snipe/project/3d53e1dd-b8bf-46b5-ba61-18ce26933166/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)
> - 🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/snipe/project/3d53e1dd-b8bf-46b5-ba61-18ce26933166/settings/integration?pkg&#x3D;alpinejs&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by snipe** [comment]
@marcusmoore - this bump seems a little too risky to blindly take. Can you test this locally and make sure nothing breaks? I know alpine can be a bit finicky. I think we use it most in the new label engine.

**Comment by snipe** [comment]
(We wouldn't commit this directly to master anyway, of course, but it bears testing.)

**Comment by marcusmoore** [comment]
@snipe Alpine is being removed in #14831 since it is bundled with Livewire 3. I'm going to get the conflict resolved and move  the PR out out of draft today (soon) so we can probably ignore this for now? It doesn't look like there is a security fix in that version.

**Comment by snipe** [comment]
Should we just close this then? If there are no security implications, AND it's going away anyway, I can just close it.

**Comment by marcusmoore** [comment]
@snipe yeah I'm thinking we should just close this one.

**Pull request closed without merging**
