### PR TITLE
Fixed #9813: Duplicate function accept-asset

### LINKED ISSUE #9813: Duplicate function accept-asset
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There are two routes with different view-templates for the same action: asset acceptance

Routes:
- https://example.com/account/accept-asset/9
```php
 # Accept Asset
    Route::get(
        'accept-asset/{logID}',
        [ 'as' => 'account/accept-assets', 'uses' => 'ViewAssetsController@getAcceptAsset' ]
    );
```
- https://example.com/account/accept/9
```php
    Route::get('accept/{id}', 'Account\AcceptanceController@create')
        ->name('account.accept.item');

    Route::post('accept/{id}', 'Account\AcceptanceController@store');        
```
There are two view for the same page:
-  snipe-it/resources/views/account/accept-asset.blade.php 
-  snipe-it/resources/views/account/accept/create.blade.php 

The first has translations, the latter gets used

I would prepare a PR to fix this issue, question is can the "old" stuff from the ViewAssetsController removed?

### PR DESCRIPTION
**Pull request by dampfklon**
# Description

The old and not longer used route https://demo.snipeitapp.com/account/view-assets/9 got remove with its controller functions and view.

The new view has now localization support, no new strings were needed. I also switch the position of the Accept/Decline Ratio Buttons and the Eula, so the user first reads the Eula and then selects Accept or Decline and if active directly below signs it.
Lastly I made small design changes to the view.

Preview after the changes:
https://imgur.com/Aj9u0Y6

Fixes #9813 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Checkout Assets with its category enabled acceptance workflow
- Open Acceptance link from confirmation mail
- Check different eula length, with and without signature for any gliches
- Accept asset

**Test Configuration**:
* PHP version: 7.3.27
* MySQL version: mariadb 10.5.9
* Webserver version: apache 2.4.46
* OS version: Docker Alpine Container

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
@inietov Can you test this PR for me when you get a moment? Thanks!

**Review by inietov — APPROVED** [review]
Thanks for this clean up on our routes. Looks good to me, works as described in my local, and I actually like more how it looks the acceptance screen now. 

Thanks again for your time putting this together!!.

**Comment by dampfklon** [comment]
As reqested in the roadmap post, I also created a v6 PR #9857

**Comment by dampfklon** [comment]
I there anything else to do, to get the pr merged?

**Comment by snipe** [comment]
@dampfklon Sorry this took so long. I'm seeing some merge conflicts that one of us will have to get handled before I can merge :(

**Comment by dampfklon** [comment]
@snipe Took me also some time to fix the merge conflicts. It's now fixed.

**Comment by dampfklon** [comment]
Would be nice if this would make it into the v6 release.

**Pull request merged**
