### PR TITLE
fix: tabs-not-clickable-on-mobile

### LINKED ISSUE #10877: V6 - Tabs not clickable on mobile
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If you view the Details of an Asset,

On Mobile (Iphone X) the Tabs on the Top are not clickable. Or better they are clickable but not non click on the Icon, only if you click the very top of the icon.

Ist there any Way to fix this...old Threds in this case are autoclosed :(

### Reproduction steps

1.Login
2.Go To Assets
3.View Details of an Asset
4.Try to click the Buttons above

### Expected behavior

It should be possible to click cleanly through the tabs on any mobile device.

### Screenshots

These Tabs are the problem

image

Just In This Area the buttons are clickable, only at the very Top of the Icon
99F973D0-F4E9-4B4C-BAA9-FC23AB8B1CC7

If the Icons are in the 2nd line they are not clickable, also when you select a button in the second line and want go back to a tab in the first line the first line is also not clickable 
4D1724EE-E707-44C3-B059-54CD81E317CC

The Error Info which appers has no exit button and is overlaying all the buttons
54616D16-BD30-4020-838C-9E7A2B322778

### Snipe-IT Version

Tested in 5.4.1 and also in V6 RC7

### Operating System

Debian 10

### Web Server

Apache

### PHP Version

7.3 and 7.4

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NojoudAlshehri**
# Description

Both issues mentioned in #10877 of button not clickable & nav bar blocking When Screen is less than 400px are fixed.

### I Modified the 'clear' property in nav::after, that improves the arrangement and alignment of elements within the navigation section.

| BUTTON NOT CLICKABLE ON MOBILE   |      NAV BAR BLOCKING      |  
|----------|:-------------:|
| Button Not Clickable |  Nav Bar Blocked |
    
Both Problems Fixed:
ezgif com-video-to-gif

Fixes #10877

## Type of change

- [x]  Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Test A: Make Screen size less than 400px (or use mobile device), Click on buttons in second lines
- [x] Test B: If There are no result to show after clicking, The Nav Bar wilĺnot be blocked by the message.

**Test Configuration**:
* PHP version:  PHP 8.0.28
* MySQL version: 10.4.28-MariaDB
* Webserver version: Apache/2.4.56
* OS version: Windows 11

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Godmartinz** [comment]
The Nav options appear to still be blocked when I test this.

**Comment by NojoudAlshehri** [comment]
Hello, @Godmartinz 
it works, Here is GIF.
Both issues of button not clickable & nav bar blocking are fixed.
ezgif com-video-to-gif

**Comment by snipe** [comment]
Can you let us know if #13077 resolves this for you?

**Comment by NojoudAlshehri** [comment]
@snipe 
yes it works.
#13077 solves the same issue.
thanks

**Pull request closed without merging**
