### PR TITLE
Issue #9157 Update .env to API_TOKEN_EXPIRATION_YEARS=15

### PR DESCRIPTION
**Pull request by JohnnyPicnic**
Getting a 401 unauthorized when using 40 years. Tried decreasing the time by 5 years until I got 15 years to work.

Fresh install on Raspbian.

### CODE REVIEW

**Comment by snipe** [comment]
That only happens on 32-bit systems, so seems better handled in documentation.

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by snipe** [comment]
Looks like this version is pretty far behind our versions. You'll need to rebase your develop and then retarget. (When I tried, there were 45 files changes in the diff.)

Again, I really think this is better handled in documentation - which is currently is - but I'd be willing to accept this PR.

**Comment by JohnnyPicnic** [comment]
Ok hopefully I did the proper thing. Most the of these things "rebase your develop and then retarget" are not known to me ;)
In my case I was moving from a Google Cloud instance to a Raspberry Pi so the error was pretty unusual as everything else was copied/moved over from a working system.

**Comment by snipe** [comment]
I'm still seeing 45 files changes here and we've got some merge conflicts now, so I'll just apply this to the develop branch myself. Thanks.

**Pull request closed without merging**
