### PR TITLE
Feature/ch16470/add remove location as option in location

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

Adds a removal button for locations from the bulk users edit screen.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

image

### CODE REVIEW

**Comment by snipe** [comment]
I don't think we need a new method for this, do we?

**Comment by snipe** [comment]
Ping?

**Comment by Godmartinz** [comment]
no we don't, Ill get this adjusted today

**Comment by snipe** [comment]
@Godmartinz Can I get an update on this?

**Comment by snipe** [comment]
I think we'd probably want to handle this the way we handle the bulk assets "remove date" functionality, just to keep it consistent. Sorry to leave you hanging so long :(

**Pull request closed without merging**
