### PR TITLE
Added history tab to accessories

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

Adds a history tab for accessories

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Can you chuck up a screenshot this one, Godfrey? Thanks!

**Comment by Godmartinz** [comment]
Uploading F94995F2-F956-4DAC-A091-9D049F9E5FD1.mov…

**Comment by Godmartinz** [comment]
https://user-images.githubusercontent.com/47435081/171474840-b406a44f-9670-4c16-9c2b-9124cfbe0f5b.mov

**Comment by snipe** [comment]
Thanks!

**Pull request merged**
