### PR TITLE
Remove old ldap

### PR DESCRIPTION
**Pull request by uberbrady**
This is the start of a cleaned-up LDAP implementation, based on our 'classic' LDAP from v4, which was replaced by the new LDAP system in v5.

Because of some issues with larger directories in v5, we ended up switching back to the v4 LDAP implementation for *sync*, but not for *login* - so effectively we were managing two, slightly different LDAP systems.

This puts us squarely back into having just one - the old one. In a lot of large environments with huge numbers of users (think: schools), our own self-built LDAP system is going to be more appropriate and customizable. It's a little less pretty to look at than the newer one, but that's life :(

Furthermore - just to add to the fun - it turns out the main way we make paginated requests - `ldap_control_paged_result` - which was already throwing deprecation errors that we had to mask in PHP v7.4 - is fully removed in PHP v8. So this also switches us over to the newfangled way of doing paginated queries. Unfortunately, it still seems to need an '@' in front of it, which I hate - but hopefully we can figure out how to get rid of that before this goes live. (BTW, I should note that the 'newfangled way' was introduced in PHP v7.3, so that should line up with the PHP minimum requirements we're talking about for Snipe-IT v6.x)

### CODE REVIEW

**Comment by uberbrady** [comment]
This: https://github.com/snipe/snipe-it/pull/9340/files was a fix that we merged previously, and I need to make should make sure we have addressed that use-case. (e.g. "no admin user/pass has been defined, just log in directly"). I suspect it might work but I'd like to be sure.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/pull/9340">Fixes #9063 Added sanity check to determine if a bind user account is set. by raelldottin · Pull Request #9340 · snipe/snipe-it</a></strong></div><div>Description
This bug was introduced in this commit: #7919
The adlap2 module binds to the AD/LDAP server using $username and $password because the third parameter in $this-&gt;ldap-&gt;auth()-&gt;at...</div></blockquote>

**Comment by uberbrady** [comment]
> This: https://github.com/snipe/snipe-it/pull/9340/files was a fix that we merged previously, and I need to make should make sure we have addressed that use-case. (e.g. "no admin user/pass has been defined, just log in directly"). I suspect it might work but I'd like to be sure.
> 
> >  GitHub**[Fixes #9063 Added sanity check to determine if a bind user account is set. by raelldottin · Pull Request #9340 · snipe/snipe-it](https://github.com/snipe/snipe-it/pull/9340)**Description
> > This bug was introduced in this commit: #7919
> > The adlap2 module binds to the AD/LDAP server using $username and $password because the third parameter in $this->ldap->auth()->at...

So, no, we don't handle that :( - what that feature added was something like this:

- *only* if an LDAP admin user and password was defined - 
- *then* all subsequent LDAP operations run as *that user* - not the one who logged in.

This makes it so that administrators don't have to grant search privileges to users who are logging in; the search can be performed by the Admin user. If we merge this PR, we will no longer be able to support that.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/pull/9340">Fixes #9063 Added sanity check to determine if a bind user account is set. by raelldottin · Pull Request #9340 · snipe/snipe-it</a></strong></div><div>Description
This bug was introduced in this commit: #7919
The adlap2 module binds to the AD/LDAP server using $username and $password because the third parameter in $this-&gt;ldap-&gt;auth()-&gt;at...</div></blockquote>

**Comment by snipe** [comment]
@uberbrady can you check in on this PR? It's been open a bit and there are some conflicts. Would love to get this into the upcoming release candidate so folks can test it. Thanks!

**Comment by uberbrady** [comment]
@snipe OK, I think I've fixed the conflicts. I had to re-do the composer install because of the conflicts on `composer.lock`, but I think the rest ought to be pretty solid. And I had to do some twiddling of the `use` statements at the top of `SettingsController.php`

**Pull request merged**
