### PR TITLE
Remove CSS that isn't respected when display is inline

### PR DESCRIPTION
**Pull request by chksome**
# Description

Remove unused width and height on .qr_text label CSS. These aren't respected when display is set to inline.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Ran Codeception tests per SnipeIT documentation. Tested in Chrome 100.0.4896.127, Firefox 91.8.0esr, and Edge 100.0.1185.50. No change in label generation.

**Test Configuration**:
* PHP version: 7.4.29
* MariaDB version: 5.5.68
* Webserver version: 2.4.6
* OS version: CentOS 7.9

# Checklist:

- [X] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [X] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
I’m showing 505 files changed here, including some of my own commits. Did you perhaps make your branch off of master and make the PR against develop?

**Comment by snipe** [comment]
Also please work with @Godmartinz to see if this would step on any of the labels work he's been doing.

**Comment by chksome** [comment]
@snipe I did and I did. My apologies, I don't do pull requests too often. I'm actually going to close this pull request and work with @Godmartinz to make sure I'm not duplicating work. I didn't know they were working on labels. If not, I'll create a new one with less derpiness. Thanks and sorry for the noise!

**Comment by snipe** [comment]
No problem :) This is how we all learn!

**Pull request closed without merging**
