### PR TITLE
Fix for location and model drop down with granular permissions.

### LINKED ISSUE #10701: Permissions Error
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have a custom group created to allow people to edit everything but not create or delete assets, models, location etc. This has worked perfectly fine until about a week ago. This could coincide with the last update I performed. 

Now when using these permissions, I select the location drop down and the model drop down list and nothing appears. With super admin permissions this works fine. I have tried changing the permissions and found when I allow the ability to create an asset this works again but I do not what people to have that ability.

### Reproduction steps

1.Edit an asset
2.Click the locations or Model drop down list
3.
...

### Expected behavior

A list of all the current locations or models should appear. 

### Screenshots

_No response_

### Snipe-IT Version

  Version v5.3.10 - build 6684 (master)

### Operating System

Winsows Server 2019

### Web Server

IIS

### PHP Version

7.4.20

### Operating System

Windows 10

### Browser

Chrome

### Version

98.0.4758.82

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

```shell
This action is unauthorized.
D:\SnipeITSource\vendor\laravel\framework\src\Illuminate\Auth\Access\Response.php#119
Illuminate\Auth\Access\AuthorizationException

public function authorize()
    {
        if ($this->denied()) {
            throw (new AuthorizationException($this->message(), $this->code()))
                        ->setResponse($this);
        }

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aranar-pro**
# Description

Fixes #10701 location and model drop down missing on user with edit permissions.  Allows user with only view and checkout/in permissions to see location drop down on checkout/in.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Test 1: checkout without edit permission: Change user permission by group, (e.g. user can view, checkout), login with user assigned to group, checkout item, load location menu.
Test 2: edit without Create permission: Change user permission by group ((e.g. user can view, edit but NOT create or delete), login with user assigned to group, edit item, load model menu, load location menu.

**Test Configuration**: 
* PHP version: 7.4.13
* MySQL version: Maria DB 10.6
* Webserver version: IIS 10
* OS version: Windows Server 2019

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
I kinda don't understand why this would be needed, since I was nearly sure I tested that the array ends up being an OR query on the gate, not an AND, but I believe you. 

Monday is coming in HARD today. :-/

**Comment by snipe** [comment]
Can you pull your composer lock out of this PR?

**Comment by snipe** [comment]
TYSM!

**Comment by aranar-pro** [comment]
Sorry. Yep. Monday.   Composer.lock removed.  I hope this helps!

**Pull request merged**
