### PR TITLE
Feature/ch16172/adding other fields to ldap sync settings

### LINKED ISSUE #9197: LDAP Import Custom Attributes
Is it possible to import additional fields during an LDAP import?
I would like to have the corresponding manager with the users.
Departments and their managers can be created, but it would be very advantageous to be able to import thousands of users correctly with the appropriate attributes.

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
  Fresh
- Version of Snipe-IT you're running
v5.1.1 build 5811
- What OS and web server you're running Snipe-IT on
Microsoft IIS, Windows Server 2019

### PR DESCRIPTION
**Pull request by Godmartinz**
Fixes #9197 #7211 

## Adds Department to LDAP settings

- [ X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by snipe** [comment]
This looks great, thank you @Godmartinz!

**Comment by valdoltra** [comment]
Based on this, Manager field and Department should be syncing?

**Comment by uberbrady** [comment]
Yes, *if* you define those fields in your LDAP settings, and those LDAP attributes that you reference **do** exist, and are set.

**Comment by valdoltra** [comment]
Manager field is missing in my LDAP settings. Also department is set in users' properties in AD but is not syncing:
image

**Pull request merged**
