### PR TITLE
Add department to asset

### PR DESCRIPTION
**Pull request by pbrink231**
This feature adds the department field to an asset.

Updates:
- Updated Departments show view to have tabs
  - Info tab
  - Users tab
  - Assets tab
- Added department column to Assets table
- Added department to Assets Api for table

### CODE REVIEW

**Comment by pbrink231** [comment]
Added Bulk editing the department on the assets table.

**Comment by pbrink231** [comment]
Changed the department view to better match other settings views.  no more details tab.  Information is now on the right similar to other views

**Comment by snipe** [comment]
What's the use case here?

**Comment by pbrink231** [comment]
Adding more to this.  Not ready for merge.

**Comment by pbrink231** [comment]
We have several departments that own their own assets.  So our IT department is responsible for their assets (computers and such).  We have a sublimation department that is responsible for their own assets.  This will allow separating assets out by owning departments.  Can later add security for only allowing to see/create assets in your department.

This will solve this case
https://github.com/snipe/snipe-it/issues/7662

And in that case I linked several other issues that this would be a base for.

**Pull request closed without merging**
