### PR TITLE
Fixes/fix location icon on dashboard

### PR DESCRIPTION
**Pull request by hawke114**
# Description

Fixed Location icon not loading on dashboard
Before:
image

After:
image

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Reloading the page once the code change was made

**Test Configuration**:
* PHP version: 8.1.7 
* MySQL version:  Ver 15.1 Distrib 10.3.34-MariaDB
* Webserver version:  Apache/2.4.38
* OS version: Raspbian GNU/Linux 10 (buster)

# Checklist:

- [X] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [X] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
I'm not able to reproduce this issue, but if anything it would likely be an issue with font-awesome, not the backend code (missing or old font files, etc).

Screen Shot 2022-06-13 at 11 08 05 AM

**Comment by hawke114** [comment]
> I'm not able to reproduce this issue, but if anything it would likely be an issue with font-awesome, not the backend code (missing or old font files, etc).
> 
> Screen Shot 2022-06-13 at 11 08 05 AM

This was after an upgrade, but I have run sha256sum on the font files from the upgraded instance, and a fresh clone of the repo and they seem to match.

**Comment by hawke114** [comment]
@snipe This issue seems to also exist in the demo instance:
image

Manually editing in the browser inspector the change I have made resolves the issue the same as it did in my environment.

**Comment by snipe** [comment]
Not able to reproduce it on the demo.

Screen Shot 2022-06-13 at 6 30 25 PM

Again, this would be a font issue not a backend issue.

**Comment by snipe** [comment]
If the only change I should be looking at in this PR is `fas` from `far`, it would have helped if that was the only change that was included. Additionally, since this is a browser issue, knowing what browser you were using would have been very helpful in order to try to reproduce.

**Comment by hawke114** [comment]
Apologies, I don't do PR's on github much. I attempted to follow the contribution guidelines. I created a branch and created a PR into develop.

**Comment by snipe** [comment]
It's ok - I suspect you were a few commits behind, which is what made it difficult to see the change you yourself were making versus the stray commits that were already there that were addressing backend issues. I've patched your changes on develop and master now, and the icons show up on Chrome. For some reason, Safari and a few other browsers were fine with the old Font Awesome Syntax, and other ones were not.

**Pull request closed without merging**
