### PR TITLE
Fixed #9869 fix view assigned assets page

### LINKED ISSUE #9869: #9709 Breaks View Assigned Assets Page
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
#9709 Breaks the `View Assigned Assets Page`. Removing the added code from https://github.com/snipe/snipe-it/pull/9709/files fixes this issue.

We have `Full Multiple Companies Support` enabled. Not all assets are in the same company. The new merge hides assets not in the same company as the user from the user's self-view. 

**To Reproduce**
1. Update to commit 9a5d9eafebb80f1992ea2c38cd36d2256445475f.
2. Enable Full Multiple Companies Support.
3. Create a test account.
4. Assign an asset to a Company test user is not assigned to.
5. Assign this asset to the test user. 
6. Log in as the test user.
7. Go to View Assigned Assets Page.
8. Verify that you cannot see the asset.

**Expected behavior**
Users should be able to see all assets assigned to them.

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.8 - build 6227 (master)
 - OS: CentOS
 - Web Server: Apache
 - PHP Version : 7.4.3

### PR DESCRIPTION
**Pull request by kcoyo**
# Description

The latest commit 9a5d9eafebb80f1992ea2c38cd36d2256445475f broke the `View Assigned Assets Page`. This commit hides assets not in the same company as the user from the user's self-view.

Fixes # 9869

GIF of issue

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Enable Full Multiple Companies Support.
Create a test account.
Assign an asset to a Company test user is not assigned to.
Assign this asset to the test user.
Log in as the test user.
Go to View Assigned Assets Page.
Verify that you cannot see the asset.

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
I’m showing 44 files changed - is that intentional? Or maybe you can rebase?

**Comment by kcoyo** [comment]
Hi @snipe, sorry about that. Looks like the `develop` branch is behind `master`. I targetted `develop`.

Should I target `master`?

**Comment by snipe** [comment]
Develop should be targeted. Develop isn't behind master though

**Comment by kcoyo** [comment]
Apologies, I'm a novice with Github. But this is what I see:
Develop behind master

I forked master and submitted my pull request from that.

**Comment by snipe** [comment]
You should be working from the develop branch and then submitting the PR against the develop branch.

**Comment by kcoyo** [comment]
Ok, I think I follow now, thank you. I'll keep that in mind for the future PRs.

The PR I'm trying to fix is PR https://github.com/snipe/snipe-it/pull/9709, which was directly merged into `master`. Hence why I don't see it in the `develop` branch.

**Comment by kcoyo** [comment]
@snipe I'll go ahead and close this PR since the bug is not in the develop branch. 

Is it possible to remove https://github.com/snipe/snipe-it/commit/9a5d9eafebb80f1992ea2c38cd36d2256445475f from master? It was a PR that got merged directly to master instead of develop.

**Pull request closed without merging**
