### PR TITLE
Feature #9378 remove deleted user from unaccepted assets report

### PR DESCRIPTION
**Pull request by sh1hab**
# Description

When a user is deleted but has still not picked up their asset, they show up in the report as 'Deleted User' and you cannot remove them. I have made neccassary changes so that the User to no longer show up on the unaccepted assets report

Feature #9378 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version: **7.4**
* MySQL version **8.0.18**
* Webserver version
* OS version 

# Checklist:

- [X] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [X ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sh1hab** [comment]
@snipe will you please look at this pull request . Thank you

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by sh1hab** [comment]
@snipe i have re-targeted this PR to point to the develop branch . Thank you

**Comment by sh1hab** [comment]
@snipe will you please check this pull req

**Comment by snipe** [comment]
I'm showing 0 files changed.... 
https://github.com/snipe/snipe-it/pull/9508/files

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/pull/9508">Feature #9378 remove deleted user from unaccepted assets report by sh1hab · Pull Request #9508 · snipe/snipe-it</a></strong></div><div>Description
When a user is deleted but has still not picked up their asset, they show up in the report as &#39;Deleted User&#39; and you cannot remove them. I have made neccassary changes so that t...</div></blockquote>

**Comment by sh1hab** [comment]
> I'm showing 0 files changed....
> https://github.com/snipe/snipe-it/pull/9508/files
> 
> >  GitHub**[Feature #9378 remove deleted user from unaccepted assets report by sh1hab · Pull Request #9508 · snipe/snipe-it](https://github.com/snipe/snipe-it/pull/9508)**Description
> > When a user is deleted but has still not picked up their asset, they show up in the report as 'Deleted User' and you cannot remove them. I have made neccassary changes so that t...

@snipe please check now . Thank you

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/pull/9508">Feature #9378 remove deleted user from unaccepted assets report by sh1hab · Pull Request #9508 · snipe/snipe-it</a></strong></div><div>Description
When a user is deleted but has still not picked up their asset, they show up in the report as &#39;Deleted User&#39; and you cannot remove them. I have made neccassary changes so that t...</div></blockquote>

**Comment by sh1hab** [comment]
@snipe will you please check this pull req

**Comment by dampfklon** [comment]
This merge broke features from #9529 
I also think this fix in its form should not longer be nesessary . As in the other pr is merged there should not longer be deleted users with pending accepantaces and old ones can be deleted.

**Comment by Pikok89** [comment]
I'm not fully aware of how github works, so my apologies in advance.
I can see that this issue has been merged into the develop branch. Am I correct to assume that this hasn't been pushed to the master branch?
I am experiencing this issue and am interested to find out when this will be made available in the master branch.
image

**Pull request merged**
