### PR TITLE
Added - allow sort of license seats tab

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

image

Fixes #Sc-19673

## Type of change

Please delete options that are not relevant.

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
What blade are we looking at here? It's kinda hard to tell based on the screenshot. If we're using BS tables via client-side, this would work, but if it's server-side data, we might need to add a few things on the back end.

**Comment by snipe** [comment]
That's pulling server-side info, so we'd need to check the `app\Http\Controllers\Api\LicenseSeatsController.php` to see if we even allow sorting on those columns.

**Review by snipe — CHANGES_REQUESTED** [review]
I don't see anything on the backend that would actually provide this sorting. Per my previous comments, we'd need to set that up on the server side, otherwise the values will be ignored.

**Comment by snipe** [comment]
Ping! :) (We can discuss in the annex tomorrow)

**Comment by Godmartinz** [comment]
totally wrong approach to fix this, closing this PR.

**Pull request closed without merging**
