### PR TITLE
Fixed #8624 #8312: Re-Added Accessories API

### LINKED ISSUE #8312: Unable to GET endpoint https://develop.snipeitapp.com/api/v1/users/id/accessories without being superuser
#### Please confirm you have done the following before posting your bug report:

- [(n/a, hosted)] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Getting "403 Forbidden" response when requesting /api/v1/users/id/accessories endpoint. If I make the API key owner a superuser, the correct response is sent when using the same API key that returned a 403 before.

**To Reproduce**
1. Log in as an admin (NOT superuser) account, which has all permissions enabled except superuser
2. Generate an API key
3. Use said key to call api/v1/users/id/accessories endpoint
4. Get 403 Forbidden response

**Expected behavior**
Since the requesting user has access to see accessories in the GUI, the API request should return a JSON formatted list of the accessories checked out to the requested user

**Screenshots**
Just a regular 403 Forbidden page.

**Server (please complete the following information):**
Hosted Snipe IT.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Insomnia
 - Version: 2020.3.3

**Smartphone (please complete the following information):**
 - n/a

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Running on the hosted version of Snipe IT, currently version v4.9.4 - build 4437

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

### LINKED ISSUE #8624: Duplicate API route
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Duplicated api route accessories missing

**Screenshots**
image

### PR DESCRIPTION
**Pull request by mzack5020**
#8312 #8624 Removed unnecessary duplicate licenses endpoint and re-added the user accessories endpoint which was left off.

# Description

The main change here is to add back in the API endpoint which allowed the API to return a specific user's accessories. This was previously implemented but removed. During the change, the duplicate license endpoint was also removed.

Fixes #8624 
Fixes #8312 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I manually made the changes to our production and test servers which are running the latest version v5.0.5-pre - build 5457 (master). This should be tested additionally to verify that other functions work; however, this was such a minor change, I have extreme doubts anything else is affected.

# Checklist:

- [X] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [X] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by mzack5020** [comment]
Fixed #8624 
Fixed #8312

**Comment by snipe** [comment]
Nice catch, thanks! Looks like someone here did some... 

copypasta

(Please don't `git blame`. I'd put money on it being me lol)

**Comment by mzack5020** [comment]
> Nice catch, thanks! Looks like someone here did some...
> 
> copypasta
> 
> (Please don't `git blame`. I'd put money on it being me lol)

Trust me - it happens to everyone. Thanks for making a great app and being so responsive.

**Pull request merged**
