### PR TITLE
Added LDAP Location attribute as alternative to OU

### PR DESCRIPTION
**Pull request by alwism**
# Description

In our Company we use LDAP attributes instead of OUs to manage locations.

Fixed #: Enabled output of errors for "LdapSync" json_summary
Fixed #: Naming from location to default_location from Fix me comment in "LdapSync"
Fixed #: Split "LdapSync" OU location management in it's own function "to improve readability"
Fixed #: Some minor code styles near stuff I touched

Added #: Multi warnings in "notifications.blade.php"
Added #: New ldap settings "ldap_location_toggle" and "ldap_location"
Added #: Hiding the "ldap_ou" in "locations/edit.blade.php" if setting "ldap_location_toggle" is on
Added #: A split function in "LdapAd" that depends on "ldap_location_toggle"
Added #: ldap location mapping "LdapSync"
Added #: Warnings if location could not be found in "LdapSync"

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Test with enabled feature

  I ran the "LDAP Sync" from the UI

- [x] Test with disabled feature
  I ran the "LDAP Sync" from the UI

**Test Configuration**:

I used the docker-compose file

* PHP version: NA
* MySQL version: NA
* Webserver version: NA
* OS version: NA

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
  (I don't know how to write a test in that case)
- [ ] New and existing unit tests pass locally with my changes
  (Unit test where not working initially for me so sry no)

### CODE REVIEW

**Comment by alwism** [comment]
This is my first contribution to Open Source. Please Point out any improvements.

**Review by uberbrady — COMMENTED** [review]
Sorry that I'm just getting to this now - this looks really good to me and I think we should take it. Let me do some testing against my test AD instance and report back.

**Comment by snipe** [comment]
@uberbrady Is this something that would still make sense? It's been left alone for a long time and is conflicty again (not OPs fault, obviously)

**Comment by uberbrady** [comment]
@snipe I think is subsumed by @Godmartinz ’s PR that does the same thing: https://github.com/snipe/snipe-it/pull/12912 . Sorry @alwism - this was a great effort on your part, we were just able to take a much smaller PR that did the same thing instead.

**Comment by uberbrady** [comment]
@alwism this is a great first contribution, and it generally is quite good. What you're going to find with most maintainers (and us) is that things that are _smaller_ and _additive_ will tend to get merged more quickly than things that are larger, or change how things work. I think there's still a lot here that's good - the renaming of location -> default_location is still great. I even like the refactoring of the per-location logic into its own method. But all of that all at once meant that we were a little more afraid of getting this merged, and we ended up accepting a much tinier PR instead.

But if this is your *first* contribution, it's *spectacular*. I can't wait to see your next one. This is really great work, and I truly appreciate the time and effort and _care_ you took in making it. Thank you. I'm sorry we weren't able to merge it.

**Comment by snipe** [comment]
Agreed - this is great work. I'm so sorry we can't take it. :(

**Pull request closed without merging**
