### PR TITLE
Fix #13515: Cannot restore backup

### LINKED ISSUE #13515: Cannot restore backup
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

I had to delete my Snipe-IT container because I wanted to add some more information to the container as a label. When I recreated the container, all the information was still there but all the uploaded images were gone (not a problem and was in the back of my mind). For this reason, I wanted to restore the previously created backup but this did not work. Via the website I always received an HTTP Error 500 and when restoring in the container using PHP artisan the error that the file was not found. I used the relative as well as the absolute file path.

KR,
BlackRose01

### Reproduction steps

1. Log In on the Snipe-It Webpage and go to Setting/Backups
2. Restore backup
---
1. Exec into the container `docker exec -ti snip /bin/bash`
2. Restore the uploads via `php artisan snipeit:restore /var/www/html/storage/app/backups/snipe-it-manual-backup-2023-08-23-13-10-31.zip`

### Expected behavior

Restore all information and images, so that they can be used.

### Screenshots

# Restore from Bash
Bild_2023-08-23_142713528

# Restore from Website

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd)

### Operating System

Official Docker Image

### Web Server

Official Docker Image

### PHP Version

8.1.2-1ubuntu2.13 | Laravel: 8.83.22

### Operating System

Windows 11

### Browser

Opera GX

### Version

LVL5 (core: 100.0.4815.82)

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

```shell
Are you sure you wish to restore from the given backup file? This can lead to MASSIVE DATA LOSS! (yes/no) [no]:
 > yes



   1/107 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
   ErrorException

  fopen(public/uploads/assets/assets): Failed to open stream: No such file or directory

  at app/Console/Commands/RestoreFromBackup.php:304
    300▕         foreach ($interesting_files as $pretty_file_name => $file_details) {
    301▕             $ugly_file_name = $za->statIndex($file_details['index'])['name'];
    302▕             $fp = $za->getStream($ugly_file_name);
    303▕             //$this->info("Weird problem, here are file details? ".print_r($file_details,true));
  ➜ 304▕             $migrated_file = fopen($file_details['dest'].'/'.basename($pretty_file_name), 'w');
    305▕             while (($buffer = fgets($fp, self::$buffer_size)) !== false) {
    306▕                 fwrite($migrated_file, $buffer);
    307▕             }
    308▕             fclose($migrated_file);

  1   app/Console/Commands/RestoreFromBackup.php:304
      fopen()

      +13 vendor frames
  15  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

### Additional context

Fresh Snipe-IT container but old database container

### PR DESCRIPTION
**Pull request by chandanchowdhury**
# Description

The restore process fails when using Docker image `snipe/snipe-it:v6.2.3`.

From `snipeit-logs/laravel.log`
```
[2024-03-05 23:30:41] production.ERROR: fopen(public/uploads/assets/assets): Failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(
code: 0): fopen(public/uploads/assets/assets): Failed to open stream: No such file or directory at /var/www/html/app/Console/Commands/RestoreFromBackup.php:304)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Console/Commands/RestoreFromBackup.php(304): fopen()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\RestoreFromBackup->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#8 /var/www/html/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#10 /var/www/html/vendor/symfony/console/Application.php(1024): Illuminate\\Console\\Command->run()
#11 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#12 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(186): Illuminate\\Console\\Application->run()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(263): Illuminate\\Console\\Application->call()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call()
.
..
...
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\NoSessionStore->handle()
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#84 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#85 {main}
"}
```

I believe the reason is the [RestoreFromBackup.php](https://github.com/snipe/snipe-it/blob/master/app/Console/Commands/RestoreFromBackup.php#L232) expects a set of directories some of which are not being created by the [docker/startup.sh](https://github.com/snipe/snipe-it/blob/master/docker/startup.sh#L20) script. So when the `RestoreFromBackup.php` tried to copy files to the destination directories which does not exists, it throws an exception.

This change creates the directories expected by [RestoreFromBackup.php](https://github.com/snipe/snipe-it/blob/master/app/Console/Commands/RestoreFromBackup.php#L232).

**Note**: I am not sure why some of the directories exists in both `private_uploads` and `uploads` while others do not e.g. accessories, assets, components etc.

Fixes #13515 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Start a container using the docker image `snipe/snipe-it:v6.2.3`
```
docker run --rm -d \
    --name "snipe-it" \
    --publish=80:80 \
    --user="$(id -u):$(id -g)" \
    --volume ./snipeit-vol:/var/lib/snipeit \
    --volume ./snipeit-logs:/var/www/html/storage/logs \
    --env-file=my_snipeit_env \
    snipe/snipe-it:v6.2.3
```
Restore from a backup zip which will fail partially i.e. files are not restored correctly.

For manual fix, run below command in the `snipeit-vol` directory on the host and run restore again which should be successful.
```shell
mkdir -p uploads/assets private_uploads/accessories private_uploads/components private_uploads/consumables private_uploads/eula-pdfs
```

**Test Configuration**:
Docker image: `snipe/snipe-it:v6.2.3`

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You usually don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by chandanchowdhury** [comment]
Apologies for the mistake, I misunderstood the documentation about `develop` branch but it make complete sense now.

Changed the target for this MR.

**Review by uberbrady — APPROVED** [review]
This looks like a great fix! We probably need to undo the `config/version.php` change, but that's easy enough to do from our side, I think.

But this begs several questions - should we have some kind of authoritative file that lists the directories that we 'care' about somewhere? And then consume that list here, as well as from the backup script? And/or should the restore script dynamically create directories as and when it needs them?

But while those are interesting questions and we should probably figure out an answer to them, this fix solves a real need, right now. So I think we should take it. Thank you for your contribution @chandanchowdhury !!!

**Comment by chandanchowdhury** [comment]
Thank you @snipe and @uberbrady for reviewing and merging the changes.

> 
> But this begs several questions - should we have some kind of authoritative file that lists the directories that we 'care' about somewhere? And then consume that list here, as well as from the backup script? And/or should the restore script dynamically create directories as and when it needs them?
> 

I was going to suggest exactly what you just mentioned. Having a authoritative lists of the directories required with purpose will definitely make it easier to work on separate components e.g. app access, back/restore.

I was thinking of putting in a config file that both PHP and shell script can read and parse.

**Pull request merged**
