### PR TITLE
Added better handling of information of asset history 

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
This adds `changedInfo()` to the action log transformer, which will interpret changes in a more readable way.

array keys have been renamed to be more readable (e.g `rtd_location_id` is now `Default Location`) in the History tab of an asset. This information will be displayed if you edit/update a single asset or multiple assets at once.

If an asset never had a supplier, default location, company, or location already assigned to it, it will be noted as 'unassigned' (example below). If supplier, default location, company, or location are removed it will go back to unassigned as well.

Before:
image

After:
image

Removed the Supplier:
image

Fixes #sc-14441

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by spencerrlongg — APPROVED** [review]
I was trying to come up with a way to check for camel case or snake case and just transform into title case with spaces, but I can't see how that'd work with the translation strings, so looks good to me!

**Comment by Godmartinz** [comment]
added `id` to the info as requested @snipe  🙂 image

**Review by marcusmoore — APPROVED** [review]
Looks good!

 One thing to consider is that we're not eager loading the related data (location, asset model, company, or supplier) so we're running more queries than necessary but I don't think we can easily eager load them in the transformer (that should happen before it hits the transformer).

I'm just pointing that out. I don't think it holds back this PR but is something we'll probably want to address in the future.

**Comment by snipe** [comment]
This looks great - thank you, @Godmartinz!

**Comment by snipe** [comment]
@Godmartinz When testing this locally, I'm getting a 500 on history:

```
[2023-08-22 05:01:23] local.ERROR: ErrorException: Trying to get property 'name' of non-object in /Users/snipe/Sites/snipe-it/snipe-it/app/Http/Transformers/ActionlogsTransformer.php:162
```

(I just changed the serial number, nothing else)

Please make this your top priority today. I can't merge to master until we've got this handled, or I'll have to cherry pick this merge out.

**Comment by snipe** [comment]
(Also, whatever the issue is here, it would probably trigger elsewhere in the new code, so please check) TY!

**Comment by snipe** [comment]
I also wonder what the query impact here might be - none of those model/company/etc queries are being eager/lazy loaded, so in the Activity Report, with many records displayed, that could be pretty hairy. Right now, I'd just like the 500 to be mitigated, but we should probably revisit this soon and make sure we're checking query counts, etc on the Activity Report page

**Pull request merged**
