### PR TITLE
Fixed input field misalignments

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
inputs were being resized to make room for the required class if required. By changing the `required` class to a pseudo class (`input:required`, `select:required`, etc) the required css highlights are applied inside of the input. 

BEFORE: 
Create Asset:
image

Create Accessory:
image

AFTER:
Create Asset:
image

Create Accessory:
image

Fixes #[sc-26893]

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Hm. I sort of liked the requiredness color being not-attached to the input item itself, but I guess I can live with this. Thanks!

**Comment by snipe** [comment]
I'm noticing a few places where the requiredness was lost (example: [`/hardware/maintenances/create`](https://demo.snipeitapp.com/hardware/maintenances/create)). I think we need to take another look at this. 

Screenshot 2024-09-28 at 1 17 29 PM

**Comment by snipe** [comment]
I see what happened here. We were using the `required` *class* on the container div, not always using the `required` HTML element. This change breaks the visual display of requiredness because not all of our required fields are flagged as `required` on the input/select element, but rather in the div class that contains it. We'll have to update all of the form fields to reflect this new approach.

**Comment by Godmartinz** [comment]
Exactly, I didnt realize that was the case elsewhere til modals. I can get the rest of the app cleaned up Monday. 🙂

**Comment by snipe** [comment]
I’m already working on it :) PR shortly

**Comment by snipe** [comment]
Unfortunately, this change means the multi-checkout-to selector doesn't get highlighted as required anymore, since we can't make non-focusable things `required`. Javascript gets angry. Not sure what the solve for this is though. :(

**Pull request merged**
