### PR TITLE
fixes non-dark mode black theme

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description Fixes odd shades of grey and black.
image
image
image
image

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, providing screenshots where practical. List any dependencies that are required for this change.

Fixes # SC-19255

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Thanks! Can I see a screenshot of the tabbed interfaces as well?

**Comment by Godmartinz** [comment]
image
image
image

**Comment by Godmartinz** [comment]
The sidebar button is in the wrong spot on mobile view..let me fix that real fast

**Comment by snipe** [comment]
Okay, so we still need to lose the underline on buttons, badges, etc.

- Go to your user's profile page (you should see an admin badge)
- Go to locations and click on a location that has something in it (assets, etc) - the tabbed interfaces there should not have an underline and the badge should be readable
- The sidenav items should not have underlines and should probably be lighter for better contrast
- On the settings page, the visited/unvisited should be the same color (and they should probably be the darker color)
- In the header, the text logo should not be underlined
- In your custom fields screenshot, the disabled buttons have a blue icon color on the button instead of white

**Comment by Godmartinz** [comment]
There was text decoration on all a.links. that I removed and colors are updated for disabled buttons and visited/unvisited links. 👍 
image
image
image

**Pull request merged**
