### PR TITLE
Added #9594:  Feature/api image uploads for v6

### PR DESCRIPTION
**Pull request by PetriAsi**
# Description
@snipe here's PR for api image support againsts develop-v6-integration as planned on #9594 . 
I have no v6 development system to test this with, but diffs  seems to look fine. It should merge well :)
Commit history is not as clean as it could , as I have _some_  work when merging, but i hope that's not a issue.

### CODE REVIEW

**Comment by snipe** [comment]
Thanks for this! Could i get you to rebase from a fresh pull? I’m seeing a bunch of stuff that isn’t your commits in here, and I like to keep the PRs clean where we can.

**Comment by PetriAsi** [comment]
@snipe I'lltry that, still learning git and starting to get idea all how complex is it for you to handle all of this. :)

**Comment by PetriAsi** [comment]
@snipe  after couple of tries and errors, rebased it successfully,  learned lot about rebasing and git.  Or so I hope. 
Running 
```bash
git rebase -i upstream/develop-v6-integration
```
and then removing unwanted commits from list was cleanest way to do it. Only one commit needed merging by hand. 

So this can be reviewed again. :)

**Comment by snipe** [comment]
Can I get some quick documentation on this? (I'm preparing the v6 docs now)

**Comment by PetriAsi** [comment]
Here's how the image data should be formatted and submitted to api.

For the json api requests, image field should be formatted as data uri,  string like:
data:@[mime];base64,[base64encodeddata]
For example like on page [File to Base64](https://base64.guru/converter/encode/file) and selecting option "Data URI -- data:content/type;base64"
```json
{

"image" : "data:@[mime];base64,[base64encodeddata]" 

}
```

It's also possible to submit image upload request as multipart/form-data to api, without json formatting. Actually all api requests can be done as form requests, that's how laravel seems to work.

SnipeitPS  powershell modules is currently using multipart/form-data for image uploads if powershell is v 7.0 or greater. That saves encoding overhead on sending side and also on server.

@snipe do you need something more to write documentation?

**Pull request merged**
