### PR TITLE
Catch Errors Around Request Notifications

### PR DESCRIPTION
**Pull request by spencerrlongg**
# Description
Happened to notice a couple more uncaught mail authentication errors while requesting assets - just wrapped them in try/catches with logging. 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by snipe** [comment]
Do we want to use error here vs warn? (Thinking of there scenario of an import gone wrong crapping al over our rollbars.)

**Comment by spencerrlongg** [comment]
Fine by me, done!

**Comment by snipe** [comment]
Thanks - I know in my heart that it's better served as an error, but if people have misconfigured their slack hook, etc, it could light up our rollbar when there's not much we can do to help them.

**Comment by spencerrlongg** [comment]
Definitely, I get it.

**Pull request merged**
