### PR TITLE
Add categories dropdown to filter by category on Assets list

### PR DESCRIPTION
**Pull request by RafaelFerreiraTVD**
This feature add a dropdown to filter the assets based on specific category.

image

### CODE REVIEW

**Comment by snipe** [comment]
We've tried this method before and it broke on mobile view and also for exports - has that been tested here?

**Comment by RafaelFerreiraTVD** [comment]
> We've tried this method before and it broke on mobile view and also for exports - has that been tested here?

No, i didn't tested yet on mobile. What is the problem with exports? (I'm not sure what this means on this context)
But if the problem persists (at least on mobile) i can try to figure out a solution for that.

**Comment by snipe** [comment]
>  What is the problem with exports? 

When we tested (and granted, this was a little while ago, so it's 100% possible that Bootstrap Tables fixed this issue), the export wouldn't respect the additional filters we had added. Something in the callback wasn't firing, so when you use the export, it would export whatever data would have been on the page without that extra filter.

If we can confirm this works, there's definitely more stuff we'll want to do with it for v5.

**Comment by snipe** [comment]
(Sorry - if I wasn't clear, if we can get this to pass UAT/mobile/accessibility testing, this would be a huge step forward for what we want to do with searches, so I'm excited!)

**Comment by RafaelFerreiraTVD** [comment]
I will test it on mobile tomorrow and let you know if it is already working! Thanks for the feedback

**Comment by RafaelFerreiraTVD** [comment]
> (Sorry - if I wasn't clear, if we can get this to pass UAT/mobile/accessibility testing, this would be a huge step forward for what we want to do with searches, so I'm excited!)

Hi @snipe, i finished the tests on mobile and is working as expected.

**Comment by RafaelFerreiraTVD** [comment]
Hi @snipe can you Review the PR?

**Comment by twsit988** [comment]
How does this work? If I want to have this on mine, do I just edit each file with the modifications you've made and I'm good to go?

**Comment by RafaelFerreiraTVD** [comment]
> How does this work? If I want to have this on mine, do I just edit each file with the modifications you've made and I'm good to go?

Hi @twsit988, yes.

Or if you want, you can clone from my own repo instead copying files one by one... 😃

You can use the following command: 
`git clone -b feature/add-categories-filter-on-assets-list git@github.com:RafaelFerreiraTVD/snipe-it.git`

I think the develop branch is not stable at this moment, and you may have some errors during the execution of the project. So, if you want to run this feature on production, checkout my branch, using the command below:

`git clone -b feature/add-categories-filter-assets-list git@github.com:RafaelFerreiraTVD/snipe-it.git`

If you have any problems during the installation or to execute the setup, create a new issue, and i'll try to help you 😃

**Comment by roborobs1023** [comment]
This can already be done without having to add anything. all you have to do is type in the category in the search field and only that category shows.

**Comment by twsit988** [comment]
> > How does this work? If I want to have this on mine, do I just edit each file with the modifications you've made and I'm good to go?
> 
> Hi @twsit988, yes.
> 
> Or if you want, you can clone from my own repo instead copying files one by one... 😃
> 
> You can use the following command:
> `git clone -b feature/add-categories-filter-on-assets-list git@github.com:RafaelFerreiraTVD/snipe-it.git`
> 
> I think the develop branch is not stable at this moment, and you may have some errors during the execution of the project. So, if you want to run this feature on production, checkout my branch, using the command below:
> 
> `git clone -b feature/add-categories-filter-assets-list git@github.com:RafaelFerreiraTVD/snipe-it.git`
> 
> If you have any problems during the installation or to execute the setup, create a new issue, and i'll try to help you 😃

Hi Rafael, I like the idea. I've implemented it, however, I noticed a slight problem. It's pulling the records up fine when I select anything that's considered "Assets" BUT when it also displays Categories under Licenses. 

Can we separate them? Only list Categories in Assets.

It'd be nice if we can have the same drop down in the Licenses, Accessories and Consumables tab and obviously only display Categories in those areas.

Hope that makes sense! Thank you!

**Comment by twsit988** [comment]
Another request, upon loading the Assets page, it appears that the first Category is already displayed; any chance of it displaying a blank one at first?

The blank one should obviously load the default which is all items or clear out the selection.

**Comment by snipe** [comment]
Hi there - thanks again so much for this. It's been a while since we heard from anybody on this, so I'm going to close this. We do have plans for a much more advanced search/filtering process, which will hopefully address this issue in a more extensible way.

**Pull request closed without merging**
