### PR TITLE
Fixed #12249: fix csv importer for serial_number field

### LINKED ISSUE #12249: Serial Number not importing from CSV
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, i´m tring ro imoprt our assets.
Everything works fine but not the Serialnumbers.
I tried for the column name Serials, serials, serial numbers
Running on Windows server 2019
Version v6.0.11 build 8758 (g61fa0bda4)

This is my import line

Item Name,Company,Location,Category,Username,Model Name,Manufacturer,Serial Number,Status,Image,Checkout Type

I saw some people having the same issue but th fix doesn´t work for me

### Reproduction steps

1. Upload CSV
2. Import
3. 
...

### Expected behavior

Importing ans updating or setting Serial number entries

### Screenshots

image

### Snipe-IT Version

v6.0.11 build 8758 (g61fa0bda4)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.2

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kenchan0130**
# Description

The importer does not work to map the serial_number field because it is searching for a KEY that does not exist.

Fixes #12249

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

```csv
Asset Tag,Manufacturer,Category,Model Name,Serial
1,Lenovo,Laptop,ThinkPad X13 Gen 3,ABCDEFG
```

1. Upload a CSV
2. Select "Import type" as "Asset"
3. Select "Serial" as "Serial Number"
4. Click "Import" button

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Hi there - thanks for this! Can you please re-target this PR to point to the `develop` branch, per [our Contributing documentation](https://snipe-it.readme.io/docs/contributing-overview)? 

You don't need to close and re-open. After you create a pull request, you can modify the base branch so that the changes in the pull request are compared against a different branch. By changing the base branch of your original pull request rather than opening a new one with the correct base branch, you’ll be able to keep valuable work and discussion.

mhuxq

Thanks!

**Comment by kenchan0130** [comment]
@snipe 
Thank you for pointing this out. I have corrected this PR.

**Comment by snipe** [comment]
I'm not sure this exactly makes sense tho? The field on the `assets` table  and `licenses` table is `serial`, not `serial_number`.

**Comment by kenchan0130** [comment]
@snipe 

I also think it should be `serial` in the context of the assets table and licenses table, as you said.
I should have correctly changed the key in the `findCsvMatch` function.

import page
HTTP requeset
payload

As you can see in the image, you can define the CSV mappings from the import UI.
I believe that the key in findCsvMatch should be `serial`, not `serial number`, as it seems to be searching for the value of value in column-mappings and this will solve the problem of not being able to define serial with arbitrary column names in CSV file.

**Comment by kenchan0130** [comment]
I also think it should be `serial` in the context of the assets table and licenses table, as you said.
I should have correctly changed the key in the `findCsvMatch` function.

import page

payload
スクリーンショット 0005-03-07 22 56 57

As you can see in the image, you can define the CSV mappings from the import UI.
I believe that the key in findCsvMatch should be `serial`, not `serial number`, as it seems to be searching for the value of value in column-mappings and this will solve the problem of not being able to define serial with arbitrary column names in CSV file.

**Review by uberbrady — APPROVED** [review]
I'm pretty sure *this* is the fix we've been looking for - we've seen some reports that Serial Number seems to silently not import unless the field has a specific, particular name. This seems to correct the error. It also looks like that one field looks very unlike the other ones throughout this `handle()` method - everything else has "computerey"-looking names - `company_id`, `category_id`, `order_number`, `purchase_cost` - and the assignment to the `$item` object looks the same:

```php
$this->item['foo_computery_name'] = $this->findCsvMatch($row, 'foo_computery_name');
```

But this one line that @kenchan0130 has fixed here *didn't* look like that.

So I feel like should probably be a pretty solid fix. I can also note that it lines up a little better with some of the work I've been doing on the front-end of the importer - so that's good too.

Excellent catch, nice sleuthing work, and thank you!

**Comment by kenchan0130** [comment]
Thanks for the review.

This is outside the scope of this PR, but the function name `findCsvMatch` may be confusing developers.

I believe there may be room for a change in the function name since within this function we are searching for the CSV and the value of the field mapping.

**Pull request merged**
