### PR TITLE
Added #9413: Asset file upload from API

### LINKED ISSUE #9413: FEATURE REQUEST: File Upload via REST API
I'd like to request a possibilty to upload files to Assets (and maybe other entities) via REST API.

I found #5007 requesting the same issues and was wondering that this still is not possible.
Seems to be a feature of high value and potential.

Alternatively, I could image a feature attaching files via an `php artisan snipeit:import` but REST API seems more suitable.

Thank you!

### PR DESCRIPTION
**Pull request by Scarzy**
# Description

Add support for uploading, listing, downloading, and deleting files on an asset via the API.

This is to enable automation with handling files on assets.

Fixes #9413 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

- [X] Upload a file
```
curl --request POST --url http://localhost:8080/api/v1/hardware/1/files --header "Authorization: Bearer xxxxxxxxxx" -F "file[]=@test.txt" --verbose
```
- [X] List the files
```
curl --request GET --url http://localhost:8080/api/v1/hardware/1/files --header "Authorization: Bearer xxxxxxxxxx" --header 'accept: application/json' --verbose
```
- [X] Get a file
```
curl --request GET --url http://localhost:8080/api/v1/hardware/1/file/1 --header "Authorization: Bearer xxxxxxxxxx" --output downloadedfile --verbose
```
- [X] Delete a file
```
curl --request DELETE --url http://localhost:8080/api/v1/hardware/1/file/1 --header "Authorization: Bearer xxxxxxxxxx" --header 'accept: application/json' --verbose
```

In all cases the web GUI, the JSON response, and the downloaded file were visually inspected to ensure they were as expected.

I have tested it successfully with the following file types;
- text file
- PDF
- JPEG

I also tried with a binary file with random contents, and this didn't work. As far as I can tell the file disappeared somewhere inside laravel, and never made it to the controller. If interested, the random file was created via;
```
dd if=/dev/urandom of=random.bin bs=1M count=1
```

**Test Configuration**:
* PHP version: 8.1.2
* MySQL version: MariaDB 10.6.16
* Webserver version: Apache 2.4.52
* OS version: Ubuntu 22.04 LTS

# Checklist:

- [X] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [X] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by marcusmoore** [comment]
@Scarzy I'll follow up on your [comment](https://github.com/snipe/snipe-it/issues/9413#issuecomment-2099208977) about testing here
>I haven't created a test for the feature yet, as I was hoping to run the existing tests first, but I am conscious that as a new feature for the API it probably needs a new test

First off, thanks for being thorough about testing. I appreciate that 😄 

What issues were you running into getting the test suite up and running? It's not part of the PR template so you might have missed it but have you seen the testing docs [here](https://github.com/snipe/snipe-it/blob/master/TESTING.md)?

**Comment by Scarzy** [comment]
@marcusmoore 

> What issues were you running into getting the test suite up and running? It's not part of the PR template so you might have missed it but have you seen the testing docs [here](https://github.com/snipe/snipe-it/blob/master/TESTING.md)?

I have read the testing page, yes.
My original issues with testing were that my host machine didn't have a suitable version of PHP available, and I couldn't get docker to behave with a clean copy of my branch, the docker image would refuse to start up (my original development was done using the standard docker image and copying my changes in/out, which I didn't deem to be suitable for testing before submission).

I have now got a clean copy of my branch running in an Ubuntu 22.04 VM, and my current error is;
`
In TestCommand.php line 62
'Class "PHPUnit\Runner\Version" not found'
`

phpunit (v9.5.10) is definitely installed, I had to install that through apt as a separate step

**Comment by Scarzy** [comment]
Ok, got past that issue. I'm not familiar with composer and didn't realise I needed to rerun the install step without the "--no-dev" argument.

I'm now able to run the testing, I get 12 fails 224 passes, the fails are;

   FAIL  Tests\Unit\CustomFieldTest
  ⨯ db name chinese                 (Failed asserting that two strings are equal.)
  ⨯ db name japanese                 (Failed asserting that two strings are equal.)
  ⨯ db name korean                 (Failed asserting that two strings are equal.)
  ⨯ db name non latin euro                 (Failed asserting that two strings are equal.)
  ⨯ db name turkish                 (Failed asserting that two strings are equal.)
  ⨯ db name arabic                 (Failed asserting that two strings are equal.)

I also had 6 failures in LDAP (primarily 'Undefined constant "App\Models\LDAP_OPT_REFERRALS"'), but as I haven't got LDAP set up, I'm now running the tests with the LDAP group excluded.
I shouldn't have gone anywhere near those languages above, is it safe for me to exclude them?

As I'm now able to run the tests, I'll get some tests for the new file uploads sorted and report back.

**Comment by marcusmoore** [comment]
@Scarzy I appreciate you pushing through this. 

I'm using [Herd](https://herd.laravel.com/) and not docker so I'm not sure of any quirks in getting the app running for development in Docker. 

> I have now got a clean copy of my branch running in an Ubuntu 22.04 VM, and my current error is;
In TestCommand.php line 62 'Class "PHPUnit\Runner\Version" not found'
phpunit (v9.5.10) is definitely installed, I had to install that through apt as a separate step

I would assume that would work but ideally the composer file will get you up and running (without that `--no-dev` flag since that skips installing PHPUnit. Have you seen the docs at the bottom of the Docker page for [developing in docker](https://snipe-it.readme.io/docs/docker#for-development)? I see you're pushing through but it might be helpful if you missed that.

If you're able to write up tests and focus on running just the ones you create you can skip the ones you mentioned giving you problems in this case.

**Comment by Scarzy** [comment]
@marcusmoore 
> If you're able to write up tests and focus on running just the ones you create you can skip the ones you mentioned giving you problems in this case.

Thanks, will do.

Can I just check; are there any tests for file interactions for existing functionality?

I was looking to see how they handled generating/using temporary files, e.g. for testing file upload through the GUI, or image upload via GUI or API. But I can't find any reference to any such tests in the tests directory.

I tried to sanity check myself on this, and running the following from the root of the snipe-it checkout, and ignoring any results relating solely to new files I've created, I get;
```
find tests/ -iname "*image*"      # No results
find tests/ -iname "*file*"      # No results
grep tests/ -R -i -e "file" -e "image"
./Feature/Api/Locations/LocationsForSelectListTest.php:    public function testLocationsAreReturnedWhenUserIsUpdatingTheirProfileAndHasPermissionToUpdateLocation()
./Feature/Api/Locations/LocationsForSelectListTest.php:            ->withHeader('referer', route('profile'))
./TestCase.php:        if (!file_exists(realpath(__DIR__ . '/../') . '/.env.testing')) {
./TestCase.php:                '.env.testing file does not exist. Aborting to avoid wiping your local database.'
```

**Comment by Scarzy** [comment]
Ok, tests for all features created.

I believe all I'm missing now is updating the API documentation. Is someone able to point me to this?

**Comment by snipe** [comment]
@Scarzy - Our documentation platform doesn't allow you to easily add docs to the API documentation, but if you let me know what you'd like added, I can do that for you.

**Comment by Scarzy** [comment]
> @Scarzy - Our documentation platform doesn't allow you to easily add docs to the API documentation, but if you let me know what you'd like added, I can do that for you.

@snipe Basically just adding the following endpoints:

/hardware/:id/files GET -> List uploaded files for asset
/hardware/:id/files POST -> Upload new file to asset
/hardware/:id/files/:fileid GET -> Download file for asset
/hardware/:id/files/:fileid DELETE -> Delete file from asset

As I believe I have now done all of my bits for this, I will change this PR to no longer be in draft.

**Comment by snipe** [comment]
Can you remove the built assets from this PR? They're going to change a lot, and I don't think they're related to your changes.

How should we phrase the instruction of uploading - not just the endpoints, but that "field `blah` should be base64 encoded", etc. *Most* people won't use this, but I want to make sure we're instructing them correctly if they choose to.

**Comment by Scarzy** [comment]
> Can you remove the built assets from this PR? They're going to change a lot, and I don't think they're related to your changes.

My apologies, you are indeed right, they were not related to my changes. My prior rebase hadn't quite gone as planned. Should be fixed now.

> How should we phrase the instruction of uploading - not just the endpoints, but that "field `blah` should be base64 encoded", etc. _Most_ people won't use this, but I want to make sure we're instructing them correctly if they choose to.

I'll get something for this sorted over the next couple of days

**Comment by snipe** [comment]
> I'll get something for this sorted over the next couple of days

Awesome, thank you!

**Pull request merged**
