### PR TITLE
corrected a link color in the dark mode yellow skin

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, providing screenshots where practical. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
@Godmartinz Thanks for this - I don't think this is actually the issue though? The problem is that the alt color is MUCH lighter than the regular row color. As I mentioned in the Clubhouse, I feel like resolving it this way might be the better choice.

```css
.table-striped>tbody>tr:nth-of-type(2n) {
background-color: var(--back-sub-alt);
color: var(--header);
}
```

But ` var(--back-sub-alt)` is way too light. We want it to be pretty close to  `var(--back-sub)`, but just a little lighter, so the same link colors and text colors are visible. 


Screen Shot 2021-06-23 at 1 04 17 PM

**Comment by Godmartinz** [comment]
Ok, I went about it via`:link` because the date and action are readable but everything else on that row is a link. Ill try and find a darker background for the row instead

**Comment by Godmartinz** [comment]
image
New changes

**Comment by Godmartinz** [comment]
image
darkened a bit more

**Comment by snipe** [comment]
Did you only fix this in the yellow skin or all of the dark skins?

**Comment by snipe** [comment]
(Also please try to remember to link in the Clubhouse ticket number in these PRs/commits.)

**Pull request merged**
