### PR TITLE
Separated Notifications and Emails: Check ins and Check outs

### LINKED ISSUE #15641: 7.0.13 CC Email alerts appear to no longer work when items are checked in/checked out
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Since the upgrade to 7.0.13, it seems that the CC Email feature no longer works.

### Reproduction steps

1. Ensure a valid email is present in Notification Settings --> CC Email.
2. Checkout an item.
3. Checkin the item.
4. Expectation is to also receive a copy of the checkout/checkin email.
5. User gets the checkout/checkin email, however nothing is sent to the email address in the CC Email field.

### Expected behavior

A copy of the checkin/checkout emails should be received.

### Screenshots

_No response_

### Snipe-IT Version

Version v7.0.13 - build 15514 (master)

### Operating System

CentOS 9

### Web Server

Apache

### PHP Version

8.3.12

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

I setup a test instance of 7.0.12 and performed the above test and emails are sent to whatever address is in the CC Email field.
So seems to be a bug in 7.0.13.

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

This separates Check in/out Notifications from Check in/out Emails. This fixes the triggers of Notifications happening twice and places the CC emails in the CC field for emails. 
mail is now structured with a `Mailable::class` and sent with the `Mail::class`
Check out/in Email markdowns have been moved to `views/mail/markdown/`

The To address behavior has changed here. the alert emails and cc email are no longer registering on the To address line. they will be handled on the cc address line. In case you need to change your third party mail app.

The from email is what is set for the env variable `MAIL_FROM_ADDR`, but it defaults to service@snipe.it.io
Below you see the To: field being the checked out to, and the CC: field being the alert emails and CC email:
image

The markdown is unchanged just relocated in the project:
image

Fixes #15641

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Godmartinz** [comment]
Tests need rework..will take a look at that tomorrow.

**Comment by Godmartinz** [comment]
@snipe All tests pass except for the ImportAsset test. Which seemed to have been asserting it imported an asset and sending a notification. Do we send importing confirmation emails?

**Comment by snipe** [comment]
@Godmartinz I honestly don't remember. I don't think so, but you'd have to look at the existing code.

**Comment by Godmartinz** [comment]
Yea, I don't see that feature present in the project as of right now. I removed it from the test.

**Comment by Godmartinz** [comment]
This should be good to go now, The tests that are failing should clear up when tests on develop are good again. 🤞 Taking it out of WIP, will double check in the morning.

**Review by marcusmoore — CHANGES_REQUESTED** [review]
I think I had a hand in leading you astray...

We actually don't want to send emails for check in/out to the addresses listed in "Send alerts to" in settings...those are supposed to get ["low inventory, license expiration, and warranty expiration"](https://snipe-it.readme.io/docs/notifications) notifications...

So for the emails that this PR is working with we should only be dealing with the cc email...

**Review by snipe — CHANGES_REQUESTED** [review]
I think these should be in try/catches when we trigger the alerts though, so we don't create 500s if someone has their email address or slack wrong.

**Comment by Godmartinz** [comment]
The alerts are wrapped in try catches in the checkoutable listener.

**Comment by snipe** [comment]
@Godmartinz isn't this actually initiating the send tho? 

https://github.com/snipe/snipe-it/pull/15681/files#diff-b463d9fd627c8705fc22d512ea776cdec9cdddf67f476c26acd28ed0c40f0de6R79

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/pull/15681">Separated Notifications and Emails: Check ins and Check outs by Godmartinz · Pull Request #15681 · snipe/snipe-it</a></strong></div><div>Description
This separates Check in/out Notifications from Check in/out Emails. This fixes the triggers of Notifications happening twice and places the CC emails in the CC field for emails.
mail is...</div></blockquote>

**Comment by Godmartinz** [comment]
it is, line 65 is the beginning of the try/catch though. does that not work the way I think it does? 🤔

**Comment by snipe** [comment]
I mean, it's easy enough to test. Change your email notification and/or webhook URL to something that isn't valid (directly in the DB so you skip validation) and tail the log to see what happens.

**Pull request merged**
