### PR TITLE
Fixes #11443 - Adds check to AcceptanceController to see if signatures are enabled

### LINKED ISSUE #11443: No signature detected error when accepting assets
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If the option _Require Signature_ in the general settings is disabled, a user can't accept an asset because of the error message " Error No signature detected. If you are using an older browser, please use a more modern browser to complete your asset acceptance." As the signature field isn't shown to the user because of the disabled option, the user is not able to accept an asset.

If I enable the require signature option, a signature field is shown and after drawing something into it I am able to accept the asset. So I guess it's just a missing or wrong "If" somewhere in the code during acceptance.

This is also reproducible in your demo instance and seems to be a new error since 6.0.6.

### Reproduction steps

1. Disable the option Require Signature in general settings
2. Create an asset in a category that requires acceptance
3. Check out an asset to an user
4. User tries to accept the asset and get the error message as cited above

### Expected behavior

User can accept an asset without signature

### Screenshots

Screenshot 2022-07-01 at 13 00 29

### Snipe-IT Version

6.0.6

### Operating System

Debian 10.12

### Web Server

Apache

### PHP Version

7.4.30

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mikeroq**
# Description

Fixes #11443. Just adds a check to the require_accept_signature setting and moves the signature processing into there. 

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version: 8.1.5
* MySQL version 8.0.29
* Webserver version Apache 2.4.41
* OS version Ubuntu 20.04.4

# Checklist:

- [x ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
This looks great - can you just back out that change to version.php?

**Comment by mikeroq** [comment]
Ok I think I got it. Excuse my noobiness!

**Comment by snipe** [comment]
Now there is a merge conflict? What the hell? I haven't pushed anything up

**Comment by mikeroq** [comment]
Could have been me! I had to google about how to remove those commits :(

**Comment by snipe** [comment]
I made a clean version here - can you take a look and make sure it does what you're looking for? #11445

**Comment by snipe** [comment]
Sorry this PR got wonky - you did the work and I'd have preferred you get the credit for it :(

**Pull request closed without merging**
