### PR TITLE
Move findLicenseSeatToCheckout back to controller.

### PR DESCRIPTION
**Pull request by mnemonicly**
After discussion, move findLicenseSeatToCheckout method back to
controller from form request.  Also cleanup one tiny bit more with null
coalesce operator (Yay php 7).

### CODE REVIEW

**Comment by snipe** [comment]
Does this method make sense in a controller? Shouldn't it be a model method that returns a value or false, and then we check for that in the controller?

**Comment by dmeltzer** [comment]
I understand where you're coming from, but most of the logic in the method I'd argue is controller logic.  I think the model logic would look like:

```
public function findLicenseSeatToCheckout($seatId)
{
    return LicenseSeat::find($seatId) ?? $this->freeSeat();
}

All of the conditionals that cause assorted error messages still feel like controller logic to me.  I moved them to an independent method to sort of encapsulate the seat finding/error checking and make the actual checkout method read a bit cleaner (During checkout, we find a license seat--If I need to know more, visit that method).  I think that any approach that created a model method out of this would result in a more complicated code base.. Unless I'm missing something :)

**Comment by dmeltzer** [comment]
There is a bug though... sec

**Comment by dmeltzer** [comment]
Fixed problem codacy found.

**Pull request merged**
