### PR TITLE
Update for #15534 - Refined gates on user bulk

### PR DESCRIPTION
**Pull request by snipe**
Just a slight revision for #15534, where we use a looser gate for starting things off, and then refine the gates based on ones that might need more permissions.

### CODE REVIEW

**Review by marcusmoore — APPROVED** [review]
I like making this more detailed  👍🏾 

One thing to note is that we only display the bulk actions dropdown if the user has the ability to delete users. Should we update that so it individually takes into account which actions should be shown?

https://github.com/snipe/snipe-it/blob/a2d4dcf6e82df284602990bf9465129e0997a27b/resources/views/partials/users-bulk-actions.blade.php#L9

**Comment by snipe** [comment]
> One thing to note is that we only display the bulk actions dropdown if the user has the ability to delete users.

I don't think that's true?

https://github.com/snipe/snipe-it/blob/9f8473e254b858042fb0ec1c89edb57fc3f93707/resources/views/partials/users-bulk-actions.blade.php#L1-L23

**Comment by snipe** [comment]
@marcusmoore I just added some gates around the dropdown menu - take a peek

**Comment by snipe** [comment]
@marcusmoore Derp - you were right about the delete gate - that's dumb. I removed that and only applied it where it matters. 

I moved merged into the delete gate though, since technically anyone who can merge a user is deleting a different user(s).

**Review by marcusmoore — APPROVED** [review]
I dig it 😄

**Pull request merged**
