### PR TITLE
Fixed #10910 : Add php redis extension

### LINKED ISSUE #10910: Docker: PHP-Redis extension is missing
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

When i configure Redis in the configuration, i have this error: ` LogicException Please make sure the PHP Redis extension is installed and enabled.` with the https://hub.docker.com/r/snipe/snipe-it docker image with tag v5.4.1 (and also alpine version) 

When i install the php-redis package on the container everything works fine and the sessions and cache are stored in Redis. 

### Reproduction steps

Config:
```
CACHE_DRIVER: "redis"
SESSION_DRIVER: "redis"
REDIS_HOST: "my-redis-fqdm"
REDIS_PORT: "6379"
```

### Expected behavior

Snipe-it is using Redis for cache and for sessions

### Screenshots

image

### Snipe-IT Version

v5.4.1

### Operating System

Docker

### Web Server

Docker (Apache)

### PHP Version

7.4.3

### PR DESCRIPTION
**Pull request by denzfarid**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, providing screenshots where practical. List any dependencies that are required for this change.

Fixes # (issue)

based on issue #10910
that currently there is no php redis extension in docker image so
can't use variable
```php
CACHE_DRIVER: "redis"
SESSION_DRIVER: "redis"
```

## Type of change
Changes to
- Dockerfile added php7.4-redis
- Dockerfile.alpine added php7-redis

Please delete options that are not relevant.

- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
I created a new Dockerfile for alpine 
```Dockerfile
FROM snipe/snipe-it:latest-alpine
RUN apk add --no-cache \
     php7-redis
```
- [x] Test B
I created a new Dockerfile for Ubuntu
```Dockerfile
FROM snipe/snipe-it:latest
RUN apt-get update -qqy \
 && apt-get install -qqy --no-install-recommends \
php7.4-redis
```

after i added the redis php extension and also changed the variable driver to
```php
CACHE_DRIVER: "redis"
SESSION_DRIVER: "redis"
```
then I also checked the redis keys, and now the redis key has been filled 😊👌

image

**Test Configuration**:
* PHP version: Latest docker image
* MySQL version : Latest docker image
* Webserver version : Latest docker image
* OS version : Latest docker image
* Redis Version : redis:6.2.5-alpine

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Nice, thanks!

**Comment by snipe** [comment]
Can you apply these changes to the `develop` branch please?

**Comment by snipe** [comment]
Can you rebase this? I'm seeing  lot of commits here that don't belong.

**Comment by snipe** [comment]
Okay, I tried to change the branch manually which is why all those other commits popped up. Can you switch to develop, do a fresh pull, apply those changes and then target the PR against develop?

**Comment by denzfarid** [comment]
@snipe okay wait, I'm working on :)

**Pull request closed without merging**
