### PR TITLE
Fixed validation for purchase cost allowed to be negative

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
Prevents users from entering negative values for purchase cost. Zero is the minimum cost allowed.

image

Fixes # SC18989

## Type of change

Please delete options that are not relevant.

- [ X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
This was tested with decimals as well, yes? "-1.00", etc?

**Comment by Godmartinz** [comment]
Just did, the numeric includes decimals 👍

**Comment by snipe** [comment]
Great - and did you check with non-numeric ("abc") and null?

**Comment by Godmartinz** [comment]
yea, the `numeric|nullable` rules were already in place 🙂

**Comment by snipe** [comment]
Yeah, but still worth testing when we make changes to validation. ;)

**Pull request merged**
